### ISSUE TITLE
Checkbox clickable surface is too wide on file upload primary key selection

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#10]
![Screen Shot 2021-07-19 at 1 07 25 PM](https://user-images.githubusercontent.com/43383835/126220676-047eb819-ba0c-486e-bfee-0a520acfb60b.png)

I was unable to include my mouse animation in the photo, but essentially, the issue is that the checkbox itself isnt the only clickable area. The checkable surface for each item is the full width of the parent container, which might be accidentally clickable during upload

**Comment by tbantle22** [comment]
Closing this. This is on purpose and I think we want to be able to click on the whole item
