### ISSUE TITLE
File upload for update ignores column names

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#103]
Updating a table with a CSV ignores column names and imports data using column order instead. This does not match the behavior in Dolt, which considers the csv column names

**Comment by tbantle22** [comment]
Relevant dolt PR: https://github.com/dolthub/dolt/pull/2105

**Comment by RenatoLopes771** [comment]
Can confirm. Dolt probably ignores .csv files headers (the first line)

**Comment by tbantle22** [comment]
Have a fix for this and https://github.com/dolthub/dolthub-issues/issues/97. Will get into production today
