### ISSUE TITLE
Dolthub doesn't allow me to create a PR from another repo into mine

### ISSUE THREAD

**Issue by RenatoLopes771** [dolthub/dolthub-issues#105]
**Describe the bug and expected behavior**
When trying to make a PR from another repo into mine (where I'm admin on mine and a reader on the other repo) it doesn't allow me, giving the message "Must have write permissions to from database to create pull request"

**To Reproduce (please include link if applicable)**
1. Fork a repo (I forked SHAQ)
2. When there's commits on the original repo, create a pull request in your forked repo with the base branch as yours and the "from" being the original repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/52989307/140617548-532a2be6-31ad-441b-bf20-390208fe2fcb.png)

**Browser info:**
 - Firefox web browser

**Additional context**

**Comment by tbantle22** [comment]
This should work now for from databases you don't have write permissions to
