### ISSUE TITLE
Create tags and branches on DoltHub

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#121]
In a presentation I was doing, I wanted the ability to show off the Releases tab. To do so, I would have needed to create a tag on the command line and push it. This made me want to be able to manage (create and delete) branches and tags on DoltHub.

**Comment by tbantle22** [comment]
Related issue: https://github.com/dolthub/dolthub-issues/issues/137

**Comment by tbantle22** [comment]
@druvv is doing branches now and will do tags next

**Comment by tbantle22** [comment]
Once you get to this, would also be great to show tags in this dropdown, kind of like how github does. Right now when you're viewing a tag nothing is populated there https://dolthub.awsdev.ld-corp.com/repositories/automated_testing/repo_with_tags_and_branches/data/v17
<img width="335" alt="Screen Shot 2022-01-21 at 12 37 19 PM" src="https://user-images.githubusercontent.com/29443194/150596847-7325e03f-0799-47a1-9a55-02f27476e089.png">
<img width="331" alt="Screen Shot 2022-01-21 at 12 38 41 PM" src="https://user-images.githubusercontent.com/29443194/150597004-932e2674-c02a-41c9-80e5-100f57894df4.png">
