### ISSUE TITLE
Repository error after pushing branch using HEAD

### ISSUE THREAD

**Issue by An0n3m0us** [dolthub/dolthub-issues#128]
Repository error by running `dolt push fork HEAD` (like with `git push -u origin HEAD`) instead of `dolt push fork $nameOfBranchGoesHere`

![image](https://user-images.githubusercontent.com/49789044/145245482-2955a2eb-11d7-4296-95dc-3c20d4f37701.png)

**Comment by tbantle22** [comment]
We're working on a fix for this. In the meantime you should be able to unblock yourself by deleting the remote branch like `dolt push fork :HEAD`

**Comment by cheshirekate8** [comment]
We've implemented a temp fix for now, and made an issue for the dolt problem. For now just push using the branch name. Here's the link to the dolt issue so you'll be the first to know when it's done :)

https://github.com/dolthub/dolt/issues/2480
