### ISSUE TITLE
Unable to access /profile after switching between google login and username/password login

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#13]
Steps to repro:
1. Be signed into Chrome as `example-account-one@gmail.com`
2. Be signed in to dolthub with a google account with `example-account-two@gmail.com`
2. Log out of dolthub
3. Log back in with a username/password account, created with `example-account-three@email.com`
4. Log back out
5. Attempt to sign back in using google account
Google doesn't ask for email/password, just says success
![Screen Shot 2021-06-15 at 2 51 26 PM](https://user-images.githubusercontent.com/43383835/122131295-d2a67680-cded-11eb-8e54-b392bfdd26cd.png)
See login success, but cant access signed in pages like /profile

**Comment by tbantle22** [comment]
Just tested this, I think this has been fixed. let me know if you see otherwise
