### ISSUE TITLE
Allow commit to branch directly

### ISSUE THREAD

**Issue by Vectorial1024** [dolthub/dolthub-issues#131]
I am not sure if I am understanding the features correctly, but everytime I try to commit to the main branch in Dolthub, I am required to make a PR to that main branch.

I understand that this is to ensure the safety of the main branch, but with reference to Github being able to "commit to main directly", would there be similar features in Dolthub?

**Comment by timsehn** [comment]
This is the repository for DoltHub issues. Thanks for submitting. 

We don't support that feature yet, preferring to send everything through the pull request workflow for safety/simplicity.

**Comment by tbantle22** [comment]
Can make the workspace/file upload processes look more similar to GitHub, where you're given the option to commit to the current branch or create a new branch -> PR.
<img width="1225" alt="Screen Shot 2022-07-14 at 1 57 21 PM" src="https://user-images.githubusercontent.com/29443194/179084668-e3de0f98-5a79-4191-840d-0f138770e12d.png">
