### ISSUE TITLE
Allow deleting branches

### ISSUE THREAD

**Issue by Vectorial1024** [dolthub/dolthub-issues#132]
I am using Dolthub from the web interface. Every time I create a PR, a branch is created, but when I merge it afterwards, that same branch is left behind and cannot be deleted.

Would there be a feature to allow us to delete branches?

Update: I have discovered that wecan delete braches generated by PRs at the PR section, but otherwise we don't seem to have any way to delete branches...? I am new here, and am unsure where to ask questions regarding how Dolthub works.

**Comment by timsehn** [comment]
This is covered in #121
