### ISSUE TITLE
Write/Preview Buttons aren't clickable in center

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#134]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to `Edit Pull Info`
2. Try to click `Write` or `Preview` in the center.
3. Notice that you have to click slightly under the center of the text

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/149643964-a1cd4e01-de95-46ae-854a-26fedf849f3f.png)

**Browser info:**
 - Desktop
 - OS/Device: Windows 10 Version 20H2
 - Browser Chrome
 - Version 95.0.4638.54

**Comment by cheshirekate8** [comment]
Fix is live! Thanks for pointing this out to us :)
