### ISSUE TITLE
Diff View can be trimmed

### ISSUE THREAD

**Issue by hasnat** [dolthub/dolthub-issues#136]
Currently diff view is strictly showing all columns; good for most cases, tho if there are large no of cols its difficult to spot differences 

A possible view option to hide columns that didn't change; combining diff info based on rows smartly pick which cols to show in diff report.

**Comment by hasnat** [comment]
> You can hide each column individually but you also want a hide unchanged columns option?

Cool. Didn't know you could hide individually. And yes; would be good to have option to hide all unchanged columns in diff view. 
Brings focus to changes.

**Comment by hasnat** [comment]
I'll also reference a slimmer diff view done here: https://github.com/paulfitz/daff/pull/167#issuecomment-792327047

**Comment by ElTragon** [comment]
Thank you for making this issue. Options now has a new feature to hide/reveal unchanged cols.
<img width="1593" alt="Screen Shot 2022-05-20 at 5 15 11 PM" src="https://user-images.githubusercontent.com/20196357/169626723-6f4ef948-0991-483f-b7b6-4fbf5548d5a9.png">
<img width="1592" alt="Screen Shot 2022-05-20 at 5 15 02 PM" src="https://user-images.githubusercontent.com/20196357/169626726-e6eab80b-cb94-4849-8489-f812eb0eeabe.png">
<img width="1618" alt="Screen Shot 2022-05-20 at 5 14 50 PM" src="https://user-images.githubusercontent.com/20196357/169626727-0a1886be-91ab-4edc-a3dc-755add72efe2.png">
