### ISSUE TITLE
Description character count not anchored 

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#144]
**Describe the bug and expected behavior**
The character count/limit will move when scrolling up. 

Expected to stay within text input.

**To Reproduce (please include link if applicable)**
1. Create a PR
2. Type in the description
3. Scroll up/down

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/150563489-9ffe95a8-4543-4e8b-a6cc-eea7c92a9205.png)
![image](https://user-images.githubusercontent.com/40151222/150563633-017e0e27-fb62-400b-a69a-e7c39a9f4d9e.png)

**Browser info:**
 - Desktop
 - Windows 10 Version 20H2 (Build 19042.1415)
 - Chrome
 - 97.0.4692.71

**Comment by cheshirekate8** [comment]
Issue has been fixed! Thanks so much for telling us :)
