### ISSUE TITLE
Deploy tab error needs padding

### ISSUE THREAD

**Issue by druvv** [dolthub/dolthub-issues#146]
**Describe the bug and expected behavior**
Deploy tab error needs padding

**To Reproduce (please include link if applicable)**
1. See here when not logged in as `andy_dev`: https://dolthub.awsdev.ld-corp.com/repositories/andy_dev/repo_with_tags_and_branches/deploy

**Screenshots**
![Screen Shot 2022-01-21 at 2 05 56 PM](https://user-images.githubusercontent.com/14025711/150608482-5f8b46ae-c509-4eb2-b130-b2b57134a3ec.png)

**Browser info:**
 - Chrome Mac

**Comment by tbantle22** [comment]
We should also include the fork button right there when someone gets that error like we do for other things
