### ISSUE TITLE
Weird behavior changing the width of the database page

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#151]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to https://www.dolthub.com/repositories/dolthub/us-housing-prices/issues)
2. Open the dev console in responsive mode
3. Make width small enough so that top tabs aren't showing
4. Refresh
5. Close dev console and try clicking on tabs (they just refresh the current page)

**Browser info:**
Chrome on Macbook

**Additional context**

**Comment by liuliu-dev** [comment]
fixed
