### ISSUE TITLE
Download table dumps in common formats

### ISSUE THREAD

**Issue by noamross** [dolthub/dolthub-issues#157]
**Is your feature request related to a problem? Please describe.**
In order for DoltHub to be a useful point of distribution of data for researchers, the data needs to be more acessible to non-dolt users.  I'd like to send people to DoltHub to access my dataset, and DoltHub be the single point of truth for that data, but I don't want to make knowing Dolt, or even SQL, a barrier to people using the data.

**Describe the solution you'd like**
Much like GitHub allows downloading a ZIP of the current viewed state of the repository, or lets people download individual files, I'd like Dolt to have a web-accessible export of a CSV or parquet dump of the database tables, all together in a ZIP or as individual files.

**Describe alternatives you've considered**
 - Asking collaborators to install/learn dolt or use the DoltHub API is too high a barrier I think.
 - Alternatively we create a CI pipeline that uses a DoltHub webhook to run a `dolt dump` process and then posts the dumped files to storage, and then add links to that storage in the README. This increases the effort and number of services to maintain.

**Comment by noamross** [comment]
I like both the query-as-csv and "release"="dump" approaches.

**Comment by timsehn** [comment]
We decided this is next up in the queue for @liuliu-dev. She is going to:

1. crank out a new database page design (1-2 weeks) 
2. do query-as-csv (1-2 weeks)
3. commit as dump, auto-generate for releases (3-4 weeks)

So we're probably looking at April 1-ish.

**Comment by timsehn** [comment]
So (2) is in production now:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5376236/158241462-80d23e38-ce97-4311-8eb0-71c242f6f581.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5376236/158241553-c589d540-8041-4749-bd26-04dd15afd422.png">

It's limited to 200 rows for now as executing arbitrary SQL on the web is a much harder problem. 

We're working on (3) right now.

**Comment by liuliu-dev** [comment]
<img width="1050" alt="Screen Shot 2022-03-28 at 1 16 39 PM" src="https://user-images.githubusercontent.com/6688812/160485662-0b2dbe21-92d6-4365-90e5-dd39ee071d7c.png">

We just got (3) out! You can now download a zip of tables by clicking that download icon.

**Comment by timsehn** [comment]
Currently we only do zipped CSVs. Would you like other formats supported? If so, maybe a new issue for each one?

Also, a release and a commit have the download link.

**Comment by noamross** [comment]
This is _excellent_, thank you!  We don't have a particular need for other formats. I would suggest having a link to download the tip of the current branch on the `Database` and/or `About` views or up in the header.

**Comment by noamross** [comment]
Ooo, I see that branch name downloads work, e.g., https://www.dolthub.com/csv/dolthub/bad-words/master 👍

**Comment by timsehn** [comment]
Still could use a link somewhere for tip of branches.

**Comment by tbantle22** [comment]
Can probably add to the branches page here @liuliu-dev 
<img width="1289" alt="Screen Shot 2022-03-30 at 1 03 24 PM" src="https://user-images.githubusercontent.com/29443194/160921243-0cac172b-e81b-4fa0-8de9-562c5b0263a2.png">

**Comment by timsehn** [comment]
Potentially we could do this here:

![image](https://user-images.githubusercontent.com/5376236/160921351-cb9a708b-aa2e-40db-b43e-11a4d0bcf6ab.png)

https://www.dolthub.com/repositories/dolthub/hospital-price-transparency-v3/branches

But this link is a little hard to get to

**Comment by timsehn** [comment]
Great minds and things :-)

**Comment by liuliu-dev** [comment]
I will work on that.

**Comment by davidgasquez** [comment]
Would it be possible to also expose the raw CSV files? Right now, to use the bad-words dataset from, say, Python, you need to unzip and load the data. Having something like `https://www.dolthub.com/csv/dolthub/bad-words/master/bad_words.csv` would be awesome to reduce that loop to just a `pd.read_csv()` call. 

It also makes it really easy to run OLAPish queries with things like [DuckDB WASM Shell](https://shell.duckdb.org/).

**Comment by liuliu-dev** [comment]
We now have the zipped CSVs available for branches:

<img width="758" alt="Screen Shot 2022-03-31 at 11 01 38 AM" src="https://user-images.githubusercontent.com/6688812/161120532-28dd1687-bdc0-461b-95dd-c7cceba04b2d.png">

**Comment by timsehn** [comment]
Resolving. Thanks for all the feedback.
