### ISSUE TITLE
Users are not receiving emails for PR comments, Issue Comments, and Merged PRs 

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#158]
I do not receive emails when db's I own receive issue comments, pr comments, when prs are merged.

**To Reproduce (please include link if applicable)**
1. From Account 1, merge pr, and check Account 1's primary email
2. From Account 1, comment on Account 2's PR and check Account 2's primary email
3. From Account 1, comment on Account 2's issue and check Account 2's primary email

 - Desktop
 - Mac
 - Chrome 97.0.4692.99

**Comment by tbantle22** [comment]
Just tested all these workflows
For #1, you shouldn't get an email when you merge your own PR. If Account 2 merges a PR that Account 1 had commented on, Account 1 does get an email
For #2 and 3 I got emails when someone else commented on my PR and issue
