### ISSUE TITLE
Bad Error Message

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#159]
When I try to run a write query on a database I don't have permissions on, it says "No data returned for workspace". This should say, "you don't have write permissions on this database" and prompt me to fork it.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/5376236/153318166-cc258d30-1d45-4ac1-b757-0142079f9612.png">

**Comment by timsehn** [comment]
It's a doltlab screenshot but I confirmed same error on DoltHub.

**Comment by tbantle22** [comment]
Ugh this is my fault. It used to say the right thing and tell you to fork.
Will fix in the morning

**Comment by timsehn** [comment]
Tests are the only way out.

**Comment by tbantle22** [comment]
Fixed and added cypress tests: https://github.com/dolthub/dolthub-cypress/pull/360
