### ISSUE TITLE
Cannot create SemVer style releases

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#182]
![Screen Shot 2022-03-18 at 12 24 17 PM](https://user-images.githubusercontent.com/43383835/159071094-42e658e9-c2e8-4756-9341-d3c8e683d54d.png)

**Comment by tbantle22** [comment]
This is an issue that comes from Dolt: https://github.com/dolthub/dolt/issues/1144

**Comment by tbantle22** [comment]
This has been fixed in Dolt (and by extension DoltHub)
