### ISSUE TITLE
Allow org admins to disable public repos for all org databases

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolthub-issues#187]
Adding an organization-wide setting that prevents any databases in the org from being made public on DoltHub would help customers who want to ensure that all their databases remain private and don't get exposed publicly.

**Comment by tbantle22** [comment]
@cheshirekate8 already added this! There's an option in settings for orgs that are subscribed to DoltHub Pro

**Comment by tbantle22** [comment]
<img width="886" alt="Screen Shot 2022-03-24 at 11 01 54 AM" src="https://user-images.githubusercontent.com/29443194/159980962-35f53a69-e40a-44ae-9248-a6a03ba14013.png">

**Comment by fulghum** [comment]
Ahh, perfect! Nice work on this feature @cheshirekate8. We had a customer ask for this and they'll be very happy to know it's available already.
