### ISSUE TITLE
Allow manual input in addition to datetime picker for datetime values

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolthub-issues#190]
The new datetime picker UI is much easier to use, but some advanced customers will still want to override that and enter in an exact date string directly. For example, datetime supports fractional seconds, but that is not currently supported by the datetime picker UI. Providing the datetime picker as the default, but allowing advanced customers to enter in a freeform date could enable both use cases.

**Comment by tbantle22** [comment]
Added a text icon when editing an input then lets you toggle between the specific input type (date, number, datetime) and a textarea
<img width="210" alt="Screen Shot 2022-03-29 at 12 53 19 PM" src="https://user-images.githubusercontent.com/29443194/160695816-fa254289-edc4-4121-91a5-3a4894916fb5.png">
<img width="271" alt="Screen Shot 2022-03-29 at 12 53 43 PM" src="https://user-images.githubusercontent.com/29443194/160695898-b555fd02-1d38-4404-8555-7ad55e98f722.png">
