### ISSUE TITLE
Download Individual tables at commit as CSV

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#194]
The zip file is nice but we've had customers ask for individual tables as CSV. The challenge here is finding a compelling UI.

**Comment by noamross** [comment]
May I suggest a drop-down/expand arrow in the commit and release logs, where expanding reveals links to each of the tables, and then CSV downloads next to the edit and query icons for each table in the sidebar.  If the sidebar is too cluttered, maybe the download link appears below the table schema in each expanded table view.

**Comment by liuliu-dev** [comment]
or we can have both the download link next to the table in the sidebar and the dropdown download options next to each commit. Instead of a dropdown for every commit, @noamross would you like to have the CSV downloading link for the latest commit next to the table?

**Comment by noamross** [comment]
Yes, that sounds good!  Next to each table, the link should be to the tip of the branch the user is currently viewing. I'd suggest this be a stable url, e.g. https://www.dolthub.com/csv/USER/REPO/TABLE/BRANCHNAME, downloading `repo_table_branchname.csv`, so that it always pulls the up-to-date data, and that for URLs to specific commits users go to the commit/release logs.

**Comment by liuliu-dev** [comment]
sounds good, thank you for the suggestion :)

**Comment by liuliu-dev** [comment]
We have individual tables available now 🎉 

We put table  downloads in the options dropdown on the database page:
![Screen Shot 2022-05-06 at 12 03 10 PM](https://user-images.githubusercontent.com/6688812/167201885-63c2688d-311c-49ea-8a3b-cc2530250099.png)

And added dropdown on commit log, release and branches pages:
![Screen Shot 2022-05-06 at 12 03 31 PM](https://user-images.githubusercontent.com/6688812/167202068-ad75f0fc-e6e5-49d6-a591-50148b926d2a.png)

![Screen Shot 2022-05-06 at 12 03 45 PM](https://user-images.githubusercontent.com/6688812/167202073-676105ad-1170-4077-bbfd-7fc1941963e2.png)

![Screen Shot 2022-05-06 at 12 04 02 PM](https://user-images.githubusercontent.com/6688812/167202074-29e08b29-5c17-4ca5-acbf-dce72e7de110.png)

Going to close this issue, thx for all the feedback :)

**Comment by noamross** [comment]
Excellent, thank you!
