### ISSUE TITLE
Attempting to save view without perms modal covered

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#197]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to a repo that you do not have write permissions to
2. Click on `Save`
3. Name the query
4. Click `Save`
5. Click `Cancel` or `X`
6. See `Query Error`

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/162114735-2d6beb79-7613-423e-8b6e-9e9be4f40020.png)
![image](https://user-images.githubusercontent.com/40151222/162114756-aebbc33c-578a-4ed8-8798-c1bbf941a10c.png)
![image](https://user-images.githubusercontent.com/40151222/162114793-a9dc6412-38ac-486f-9a41-534ec9c755c2.png)

**Browser info:**
 - Desktop
 - Windows
 - Chrome 
 - 99.0.4844.84

**Comment by tbantle22** [comment]
This has been fixed
