### ISSUE TITLE
geometry type values are not displayed/gives error on table display

### ISSUE THREAD

**Issue by jennifersp** [dolthub/dolthub-issues#203]
Displaying table that has geometry type gives this error:
```
No table data found
runtime error: invalid memory address or nil pointer dereference
```

- Go to [this link to table with geometry types that has not null values](https://www.dolthub.com/repositories/jennifersp/test/data/main/geom_types)

<img width="992" alt="Screen Shot 2022-04-19 at 10 17 09 AM" src="https://user-images.githubusercontent.com/44716627/164059554-ff702248-07f6-4359-a060-a867fbae2a08.png">

**Comment by tbantle22** [comment]
To recreate the table:
```sql
CREATE TABLE `geom_types` (
  `pk` int NOT NULL,
  `gm` geometry DEFAULT NULL,
  `ls` linestring DEFAULT NULL,
  `pt` point DEFAULT NULL,
  `pg` polygon DEFAULT NULL,
  PRIMARY KEY (`pk`)
);

INSERT INTO `geom_types` VALUES (2, point(1,2), linestring(point(0,0),point(1,2)), point(1,2),
polygon(linestring(point(0,0),point(8,0),point(12,9),point(0,9),point(0,0))));
```

**Comment by tbantle22** [comment]
I fixed the dropped error [here](https://github.com/dolthub/ld/pull/9545) so we're getting an error now:
<img width="931" alt="Screen Shot 2022-04-25 at 3 15 14 PM" src="https://user-images.githubusercontent.com/29443194/165183820-b378abf5-4fea-4b20-b3d9-524b6970cce5.png">

The error is coming from [this line](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/row/noms_row.go#L82) in Dolt, where `col.Kind == Geometry` and `val.Kind() == Point`
