### ISSUE TITLE
Make a Create View button on DoltHub

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#206]
Just had a customer say he tried to create a view on DoltHub but it was not supported.

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/5376236/165186492-10700fee-31db-42ea-b5a3-4423436871e6.png">

This made him think Dolt did not support views. I worry that users think what is supported on DoltHub is what Dolt supports. Where possible we should return results for every query on DoltHub. Where we blacklist, we should say, supported on dolt locally and put the steps needed to do locally.

**Comment by tbantle22** [comment]
The query should be `create view [name] as select * from sales` and it should work.

We should add a "Create View" button somewhere though that generates this query for you

**Comment by ElTragon** [comment]
Done
