### ISSUE TITLE
Can't go back from the docs site after clicking Get Started with Dolt

### ISSUE THREAD

**Issue by druvv** [dolthub/dolthub-issues#209]
Environment:
- Browser: **Safari**

Repro Steps:

1. Click on the `Get Started with Dolt` button on homepage.
![Screen Shot 2022-01-14 at 4 51 04 PM](https://user-images.githubusercontent.com/14025711/149602283-85d5d4d3-b560-4a61-9b63-1cc175746999.png)

2. Press the back button on browser

Nothing happens.

**Comment by ElTragon** [comment]
Seems to work on Safari now, both if signed in or logged out
