### ISSUE TITLE
Clicking Database on a deleted branch page does not go to main

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#214]
**Describe the bug and expected behavior**
Take this repo for example: https://www.dolthub.com/repositories/siragathon/us-jails/data/siragathon%2Fimport-1651448064 

He has since deleted that branch, but clicking database does not do what I would expect by taking me back to main.

**To Reproduce (please include link if applicable)**
1. [Go to here](https://www.dolthub.com/repositories/siragathon/us-jails/data/siragathon%2Fimport-1651448064 
)
2. Click on `Database`

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/166461762-258ba192-4cc1-487f-b2fb-7ac4b74ef695.png)

**Comment by tbantle22** [comment]
Ah this is a good one. We maintain the current branch as you click around a database, but we should add a check for if the branch exists and use the default branch if not
