### ISSUE TITLE
Deploy tab without write perms should prompt you to fork

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#219]
Right now if you have write perms to a repo and go to the deploy tab you get this error:
![](https://cdn.discordapp.com/attachments/746418937498959953/973364216201367582/unknown.png)

Instead you should be prompted to create a fork (like we do when you try to run an update query without write perms) and then be routed to the deploy tab of your fork

**Comment by ElTragon** [comment]
Starting

**Comment by ElTragon** [comment]
Done.
The site now prompts you to sign in, if needed.
If the user does not have permission to deploy the database, then the site prompts you to make a fork and routes you to the fork to deploy
![Screen Shot 2022-05-13 at 3 04 59 PM](https://user-images.githubusercontent.com/20196357/168674546-63133815-388b-4181-b12d-a5787afabd07.png)
<img width="1159" alt="Screen Shot 2022-05-16 at 11 27 47 AM" src="https://user-images.githubusercontent.com/20196357/168674681-4633536a-fa8b-42d1-ac38-a4c167d412f6.png">

**Comment by ElTragon** [comment]
User it redirected away
