### ISSUE TITLE
Change default queries to use new index scan behavior

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#223]
Right now when you go to a table, the default query in the sql editor is `SELECT * FROM [tablename] LIMIT 200`

These should be changed to use the new index scan behavior by adding an order by with the primary keys:
`SELECT * FROM [tablename] ORDER BY [pk_col_1] ASC, [pk_col_n] ASC LIMIT 200`

**Comment by ElTragon** [comment]
Now the SQL filters for keys and uses
<img width="1606" alt="Screen Shot 2022-05-24 at 2 01 35 PM" src="https://user-images.githubusercontent.com/20196357/170306641-4d63de44-0fa9-49af-b86f-5abfd424f26e.png">
<img width="1515" alt="Screen Shot 2022-05-24 at 2 01 29 PM" src="https://user-images.githubusercontent.com/20196357/170306647-d39a6975-ee3b-4ad5-b21a-76d32dc757ab.png">
 this for the default query. We also added an explanation of the this query.
