### ISSUE TITLE
Allow download of CSVs from private repositories using API token

### ISSUE THREAD

**Issue by noamross** [dolthub/dolthub-issues#229]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to programmatically fetch data from the various CSV endpoints in a repo when the repo is private.  

**Describe the solution you'd like**
Allow users to make a GET request for a CSV or ZIP URLs in private repositories like `https://www.dolthub.com/csv/user/repo/branch/table`, `https://www.dolthub.com/csv/user/repo/commit_hash`, using their API token in the authorization header. 

**Describe alternatives you've considered**
The API doesn't provide bulk export and currently the only way to do this is to spoof a browser session.

**Additional context**
While one could also put CSV endpoints under `api/`, having the same URLs would make it easier to to switch between developing against a private and public repository.

**Comment by timsehn** [comment]
Great feature request. @liuliu-dev Can you start this after the current mobile sprint?

**Comment by liuliu-dev** [comment]
can use these commands to get CSV files

`curl -H "Authorization: token $DOLTHUB_TOKEN" https://www.dolthub.com/csv/owner/private-database/branch/tablename`
(with `token` in lowercase)

or `curl -H "Authorization: $DOLTHUB_TOKEN" https://www.dolthub.com/csv/owner/private-database/branch/tablename`
(without the key "token")
