### ISSUE TITLE
Commit read-only view

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#230]
<img width="1356" alt="Screen Shot 2022-06-02 at 3 07 34 PM" src="https://user-images.githubusercontent.com/20196357/171746643-c1b5c388-72ff-4133-a933-d3ebfa64d477.png">

Currently people can checkout branches and navigate this page. I think I might be nice to let the user checkout a commit to browse the site in read-only view to see how the data was at the point of the commit.

If the user wants to edit/change anything, then the user should be prompted to create a branch.

This would issue allow a version of this but can pollute the user's branches.
https://github.com/dolthub/dolthub-issues/issues/207

**Comment by tbantle22** [comment]
This is a duplicate of https://github.com/dolthub/dolthub-issues/issues/35
