### ISSUE TITLE
Branch Protection Rules

### ISSUE THREAD

**Issue by mkerollos** [dolthub/dolthub-issues#231]
It would be fantastic if dolt gave branch protection rules (similar-ish to GitHub).
Things I'd love to see:
* Prevent direct commits to protected branches (e.g. must PR into main)
* Prevent branches from being deleted
* Assign mandatory reviewers on PRs for protected branches

EDIT:
I did see that some of this is hinted at already being on your roadmap here:
https://docs.dolthub.com/concepts/dolthub/prs#difference-between-github-pull-requests-and-dolthub-pull-requests
So potentially a duplicate.

**Comment by tbantle22** [comment]
I split this out into separate issues. We'll get started next week and address them in this order:
1. https://github.com/dolthub/dolthub-issues/issues/232
2. https://github.com/dolthub/dolthub-issues/issues/233
3. https://github.com/dolthub/dolthub-issues/issues/234
4. https://github.com/dolthub/dolthub-issues/issues/235

**Comment by mkerollos** [comment]
🤦‍♂️ my apologies, I should have raised this on DoltHub and not Dolt!
Love your work!

**Comment by liuliu-dev** [comment]
Hi @mkerollos, you can now prevent branches from being deleted  🎉

To set branch protection rules:
go to Settings -> Branch Protections -> pick a branch ->Add protection 

![Screen Shot 2022-07-11 at 2 38 06 PM](https://user-images.githubusercontent.com/6688812/178363460-a9b9d04c-f3c3-492a-a888-8b2fb6b8bef5.png)

I will work on making a branch not being able to be force-pushed next :)

**Comment by liuliu-dev** [comment]
Hi @mkerollos , we just added another protection rule: preventing force push 🎉
I will work on adding reviewers next, thanks for the feature requests! 

<img width="648" alt="Screen Shot 2022-07-20 at 2 43 23 PM" src="https://user-images.githubusercontent.com/6688812/180088220-1c5f3da2-51cf-4e9e-ba04-d0168b4d5aa2.png">

**Comment by liuliu-dev** [comment]
Now users with write permissions can add reviewers (users with read permissions) on the pull details page, and reviewers can review/approve/reject the PR on the pull details page or diffs page.

![Screen Shot 2022-08-10 at 1 36 03 PM](https://user-images.githubusercontent.com/6688812/184015830-f3e0d48d-4568-4b3a-b67f-3b6a69d847ab.png)

**Comment by liuliu-dev** [comment]
We can now apply approval-required protection to branches. Pull requests can not be merged into the protected branches until they get at least one approval from reviewers.

![Screen Shot 2022-08-11 at 2 34 17 PM](https://user-images.githubusercontent.com/6688812/184246431-2ec4bfbe-f0ec-4127-ad5b-0cbc1f85ac6f.png)

**Comment by liuliu-dev** [comment]
Hi @mkerollos , we got the last branch protection rule out: Prevent direct commits to protected branches.
This rule will be automatically checked if `require approval` protection is activated. 

![Screen Shot 2022-11-09 at 2 13 20 PM](https://user-images.githubusercontent.com/6688812/200953279-2bb898d9-a48a-4b46-9a56-c886fbf82df1.png)

I'm closing this issue as completed. Thanks for this great feature request, it was fun working on it! Let us know if you have any feedback:)
