### ISSUE TITLE
Assign mandatory reviewers on PRs for protected branches

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#234]
Admins can add mandatory reviewers to a protected branch. When someone creates a PR against the protected branch these users are added as reviewers and the PR cannot be merged until they approve

**Comment by liuliu-dev** [comment]
working on this now, PR: https://github.com/dolthub/ld/pull/10826
some changes are made: instead of mandatory reviewers, we require a review approval before merging for the protected branch.

**Comment by liuliu-dev** [comment]
live now.
