### ISSUE TITLE
No common ancestor does not refresh after changing base branch

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#237]
**Describe the bug and expected behavior**
When creating a PR, if you select a branch that does not have a common ancestor (such as `json_cols` on dolthub/museum-collections), and then select a branch that does (such as `main`), the `no common ancestor` error message does not go away.

**To Reproduce (please include link if applicable)**
1. Go to [[Pull Requests on `](https://www.dolthub.com/repositories/dolthub/museum-collections/pulls/new)](https://www.dolthub.com/repositories/dolthub/museum-collections/pulls/new)
2. Click on `Base branch`
3. Scroll down to `json_cols`
4. Click on `From branch:` 
5. Select branch with common ancestor

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/173922246-7ea006b3-0228-485b-acf7-bd714d681896.png)
![image](https://user-images.githubusercontent.com/40151222/173922259-7f740e84-b3de-462f-8e4c-c01178d25c03.png)

**Browser info:**
 - Desktop
 - OS/Device: Windows 10
 - Browser: Chrome
 - Version 102.0.5005.115

**Additional context**

**Comment by ElTragon** [comment]
I'm starting on this now
