### ISSUE TITLE
Dolthub website hangs when starting a Hosted Dolt Preview

### ISSUE THREAD

**Issue by armstjc** [dolthub/dolthub-issues#242]
![Screenshot 2022-06-29 103501](https://user-images.githubusercontent.com/70788681/176463539-cd75de75-a1d6-432c-bb1f-cdb6b151c219.jpg)
![Screenshot 2022-06-29 103446](https://user-images.githubusercontent.com/70788681/176463543-1e1a722d-90b0-4e59-aed2-1d99790c9c82.jpg)

When attempting to start a Hosted Dolt Preview, the process hangs, and doesn't return back a host, port, username, or password.

Database is armstjc/cfbFastR-DB in dolthub.

**Comment by tbantle22** [comment]
This should be fixed now. I was able to fork and successfully deploy your database. Let us know if you still have issues
