### ISSUE TITLE
Branch is not pinned as you navigate around the database page

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#249]
I've noticed this before and a customer reported it as well.

"when navigating through tabs, coming back to the database tab it reverts back to main branch - easy to make use errors and make changes to main instead of your branch"

**Comment by tbantle22** [comment]
The solution to this is kind of similar to what we did for navigating from the database tab -> branch list -> create branch list form and maintaining the branch

**Comment by ElTragon** [comment]
I'm making good progress on this, I should be able to close this very soon.

**Comment by ElTragon** [comment]
Done, the branchName now follows as you navigate the tabs
