### ISSUE TITLE
Add cell buttons to data diff cells

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#250]
Similar to cell buttons on data tables, we can add cell buttons that edit data (drop column, delete row, update cell value) to diff data cells. In combination with allowing workspaces to [commit directly to a branch](https://github.com/dolthub/dolthub-issues/issues/131), this would let users easily make changes directly to PRs

**Comment by ElTragon** [comment]
Hey Im starting on this now
