### ISSUE TITLE
API Demonstration for multi-table download saves a .zip file as a .csv

### ISSUE THREAD

**Issue by armstjc** [dolthub/dolthub-issues#254]
https://docs.dolthub.com/concepts/dolthub/api#all-tables
The demonstration code in this section for python works, except for mislabeling a .zip file as a .csv file.
![image](https://user-images.githubusercontent.com/70788681/179530423-94196b46-77b7-469e-9820-d89a19602cba.png)
![image](https://user-images.githubusercontent.com/70788681/179530457-39372675-9dab-492f-b664-f9670e761323.png)

Fixing this typo in the docs properly saves the resulting file as a .zip file, with the correct file extension.
![image](https://user-images.githubusercontent.com/70788681/179530708-8b5cd0ad-f985-4ba2-9214-f3e323e8d4c6.png)
![image](https://user-images.githubusercontent.com/70788681/179530754-c5dd9f4c-4b90-4454-b773-8edadfc649b9.png)

**Comment by liuliu-dev** [comment]
fixed now, thanks for the issue :)
