### ISSUE TITLE
Emails are are case-sensitive

### ISSUE THREAD

**Issue by xvr-hlt** [dolthub/dolthub-issues#259]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Invite someone to join a team (at say `firstname.lastname@gmail.com`).
2. User signs up with `Firstname.Lastname@gmail.com`.
3. User receives a notification saying cannot find invitation.
4. User adds `firstnam.lastname@gmail.com` to account as secondary email.
5. User can accept invitation to join team. 

**Additional context**
Expected behaviour on my end would be that emails are case insensitive wherever they're relevant.

**Comment by tbantle22** [comment]
Thanks for letting us know! Looking into this today

**Comment by liuliu-dev** [comment]
Hi @xvr-hlt , the bug should be fixed now, thanks for reporting the issue :)
