### ISSUE TITLE
Markdown hard wrap

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#26]
Hey I've got a README that has a couple of paragraphs. Your markdown converter doesn't enable hard wrap/break (forgot) so my multi-line single-paragraph looks uhhh a bit funky: https://www.dolthub.com/repositories/andrew-chen-wang/words-in-political-media/doc/main/README.md Is that intentional?

**Comment by ElTragon** [comment]
Thank you for posting this, does this fix work for you.
<img width="1363" alt="Screen Shot 2022-05-27 at 9 46 26 AM" src="https://user-images.githubusercontent.com/20196357/170743756-58fa2736-321c-4dc0-b039-7746d978b326.png">
<img width="1377" alt="Screen Shot 2022-05-27 at 9 46 15 AM" src="https://user-images.githubusercontent.com/20196357/170743766-c53fb012-b13b-430e-9468-0c96890f6d65.png">
<img width="1376" alt="Screen Shot 2022-05-27 at 9 45 55 AM" src="https://user-images.githubusercontent.com/20196357/170743772-dc86aac7-d8e6-40cc-85e4-a9b19c4a26a4.png">

**Comment by ElTragon** [comment]
https://github.com/dolthub/ld/pull/9944
