### ISSUE TITLE
Login after verify email not working

### ISSUE THREAD

**Issue by katiemcculloch** [dolthub/dolthub-issues#27]
Apparently worked in Safari incognito and not in Chrome _non-icognito_:

```
For verifying, using Chrome to verify completely does not work. The sign in modal prevents you from clicking the google oauth button.
```

Chrome version: 89.0.4389.90

Full report is from `ACW` in `#dolthub` Discord chat

**Comment by tbantle22** [comment]
I believe this has been fixed with the new google oauth button
