### ISSUE TITLE
A diff summary error appears if you drop any col before a pk

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#271]
I get the following error `diff summary will not compute due to primary key set change with table nextRepo
` when I try to drop some col before all `pk cols`.

Repo
1.   create a new table with a single, so that some data col appears before all pk cols
<img width="497" alt="Screen Shot 2022-08-08 at 9 59 23 AM" src="https://user-images.githubusercontent.com/20196357/183472734-1f1a1848-2659-4f52-81e4-d6962bd9449b.png">

2.  Once merged, view the table.
3.  Drop some column before all `pk cols`. 
4.  Once the site takes you to a workspace, click on the `Cumulative Diff` then you will see the following error.
<img width="1517" alt="Screen Shot 2022-08-08 at 9 52 34 AM" src="https://user-images.githubusercontent.com/20196357/183472831-85bf16a5-5bcf-49bb-b30d-776ef3be3e87.png">

**Comment by ElTragon** [comment]
No bug appears if the pk is in the first col

**Comment by tbantle22** [comment]
This is a dolt bug https://github.com/dolthub/dolt/issues/4037

**Comment by druvv** [comment]
This was closed by https://github.com/dolthub/dolt/pull/4049
