### ISSUE TITLE
Keyless table incorrectly edited using `Spreadsheet Editor`

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#276]
If you edit a keyless table using the `Spreadsheet Editor`, then it merge the changes then you end up with a new table containing both the original table and the new table with the correct changes.

Repro
Create a keyless table like the following issues
<img width="501" alt="Screen Shot 2022-08-09 at 11 45 27 AM" src="https://user-images.githubusercontent.com/20196357/183738279-4cac527b-0036-45ee-8890-26ae2cff8081.png">

On editing some cell

1.  On any tab open this side menu and click on the pencil icon of your keyless table
<img width="383" alt="Screen Shot 2022-08-09 at 11 53 37 AM" src="https://user-images.githubusercontent.com/20196357/183738902-cd323e47-5b0e-436d-92d9-6d1ef0aa27ca.png">

2. Click on the box with`Spreadsheet Editor`
3. The `Spreadsheet Editor` will open up, edit a single cell. ex(middle 3 -> 4) Then click on `Upload Table`
4. Once the `review` page loads, you should see something like the following image. You should see instead a dropped row and added row with only the edited celling being the difference. To continue click on `next` when it appears. Then click on `Commit` when it appears. The site should load and take you so a pr.
 <img width="452" alt="Screen Shot 2022-08-09 at 11 58 54 AM" src="https://user-images.githubusercontent.com/20196357/183741529-cdada22c-2a86-4a1b-a767-e6ef8b87939a.png">
5. Once the PR loads click on merge.
6. Once merged navigate the the side menu from step one, but click on the play icon.
7. The site need to be refreshed a couple times but something like the following image should be shown.
<img width="411" alt="Screen Shot 2022-08-09 at 12 05 04 PM" src="https://user-images.githubusercontent.com/20196357/183740791-ca897f66-4215-4d70-9a93-37564b2cd4d1.png">

The same thing happens if you add or drop a row. The table shown will be a new table containing both the original table and the a table with the correct changes made.

**Comment by liuliu-dev** [comment]
This is not a bug. when using spreadsheet for editing, the default method is `update`, which will insert the rows instead of modifying them. switch to `overwrite` or `replace` if changing a cell.

![Screen Shot 2022-12-12 at 1 29 07 PM](https://user-images.githubusercontent.com/6688812/207158501-cd44046e-3211-4f16-bcca-47c6bb7f2946.png)
