### ISSUE TITLE
Can not drop a row using `Spreadsheet Editor` on a pk table

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#277]
For any pk table, if you drop a row with the `Spreadsheet Editor` then on the `review` step you get the following error `No changes found from file upload. Please upload a new file`. While if you backtrack to the `upload` step you can still see the changes you made.

Repro.
1. Create any table with pks.
2. On any tab open side menu and click on the pencil icon of your created pk table
3. Click on the box with `Spreadsheet Editor`
4. The Spreadsheet Editor will open up, drop some row. Then click on Upload Table
5. Once the review page loads, you should see something like the following image. You should see instead a dropped row being the difference.
<img width="1158" alt="Screen Shot 2022-08-09 at 12 45 58 PM" src="https://user-images.githubusercontent.com/20196357/183747779-16ea24a1-1233-4c3f-b9ef-7735acb38a54.png">

**Comment by liuliu-dev** [comment]
similar to https://github.com/dolthub/dolthub-issues/issues/276

for table with primary keys, would need to choose `replace` or `overwrite` to drop a row
