### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolthub-issues#286]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to https://www.dolthub.com/repositories/knutwannheden/lobbywatch/query/master?name=unexpected-token-error&active=Queries
2. Wait
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/408765/185053161-b9a0943a-5851-448f-9416-4195d2489df6.png)

**Browser info:**
 - Desktop
 - OS/Device: Windows 10
 - Browser Edge
 - Version 104

**Additional context**

**Comment by tbantle22** [comment]
The error message has been fixed. It now shows a more user-friendly timeout error. These kinds of queries are kind of slow on dolthub right now, but we're working on it!
<img width="1101" alt="Screen Shot 2022-08-19 at 3 49 18 PM" src="https://user-images.githubusercontent.com/29443194/185716686-6d562429-d7fd-4bf0-9d72-81b77ddaa629.png">
