### ISSUE TITLE
More than one workspace is created if you edit some table without permissions 

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#288]
Repo:

1. Go to some repo where you don't have permissions to edit
2. Edit some table with pks
<img width="1565" alt="Screen Shot 2022-08-18 at 11 33 32 AM" src="https://user-images.githubusercontent.com/20196357/185468823-f9b35dd6-d89b-47b7-837b-6060bd232e25.png">

The workspace the site lands you on can sometimes be incorrect and extra workspaces can be created too

<img width="1190" alt="Screen Shot 2022-08-18 at 11 35 50 AM" src="https://user-images.githubusercontent.com/20196357/185469403-d357e81b-ed34-41f1-86a4-c7a33d7fa490.png">
<img width="1076" alt="Screen Shot 2022-08-18 at 11 35 42 AM" src="https://user-images.githubusercontent.com/20196357/185469371-17fcb199-958f-441c-8d79-9b88d37aabf0.png">

**Comment by ElTragon** [comment]
I think this is fixed now

**Comment by ElTragon** [comment]
This seems to still be and issue with Diff tables
https://github.com/dolthub/dolthub-issues/issues/347

**Comment by liuliu-dev** [comment]
this is fixed with the fork modal show up.
