### ISSUE TITLE
Make column names sticky on diffs page

### ISSUE THREAD

**Issue by liuliu-dev** [dolthub/dolthub-issues#289]
be able to see column names after scrolling

**Comment by tbantle22** [comment]
It's really old but we have an issue for this for the table columns here: https://github.com/dolthub/dolthub-issues/issues/64. We've talked about doing this before but it only really works if you make the columns a fixed width

**Comment by liuliu-dev** [comment]
> It's really old but we have an issue for this for the table columns here: #64. We've talked about doing this before but it only really works if you make the columns a fixed width

i see
zach made an issue about column width: https://github.com/dolthub/dolthub-issues/issues/238
could these two be solved together?

**Comment by tbantle22** [comment]
Yeah would need a fixed width rather than a max width, but would solve that issue too. Need to figure out how to better display text that goes beyond the fixed width though

**Comment by liuliu-dev** [comment]
> 

kk 
will look into text width then
