### ISSUE TITLE
disable the create pull request button if there are no changes

### ISSUE THREAD

**Issue by liuliu-dev** [dolthub/dolthub-issues#302]
repro:

go to https://dolthub.awsdev.ld-corp.com/repositories/liuliu/json-diff-example/data/liuliu%2Fworkspace-1662065573

click `make null` on the `NULL` cell:
![Screen Shot 2022-09-01 at 2 01 47 PM](https://user-images.githubusercontent.com/6688812/188012346-ba6ed898-151b-43b2-adc3-5f3ddbd01cd9.png)

this will create a workspace with no changes:
![Screen Shot 2022-09-01 at 1 52 48 PM](https://user-images.githubusercontent.com/6688812/188012486-de9a9910-caa7-433b-92d1-c33f7b3d8606.png)

then create a pull request, and will get a PR with no diff:
https://dolthub.awsdev.ld-corp.com/repositories/liuliu/json-diff-example/pulls/24?refName=liuliu/workspace-1662065573

should probably disable the create pull request button if there are no changes

**Comment by tbantle22** [comment]
We should probably disable the make null button for null cells too
