### ISSUE TITLE
"A bad row was encountered:" error while editing with spreadsheet 

### ISSUE THREAD

**Issue by taliakustin** [dolthub/dolthub-issues#310]
Hi I have tried editing my data using the spreadsheet on dolthub and encountered the following error:

A bad row was encountered: ..... CSV reader expected 22 values, but saw 10. 
Some columns are indeed empty but the schema allows it so I'm not sure why I get this error.

Thanks for the help

**Comment by fulghum** [comment]
Hey @taliakustin, thanks for reporting this one. I've moved the issue over to the DoltHub-issues repo so our DoltHub team can take a look. 

Do you have any more details on repro steps to share to help them debug? Is there any public database on DoltHub that reproduces this issue with the spreadsheet editor?

**Comment by taliakustin** [comment]
Hi @fulghum - Thanks!
I have created a public dataset that reproduces the same error - it is the table debug under taliakustin / debug

**Comment by timsehn** [comment]
@liuliu-dev will take a look at this one today.

**Comment by liuliu-dev** [comment]
Hi @taliakustin, thanks for the info, I'm able to repro, I'm looking into it now.

**Comment by liuliu-dev** [comment]
This error occurs when there are line breaks in the cells, line breaks in the CSV file are used as a row terminator, so a row with line breaks in text fields will be read as multiple rows when the CSV reader reads it.

I'm still working on a workaround, I will let you know.

**Comment by liuliu-dev** [comment]
Hi @taliakustin, this should be fixed. Thanks for reporting the issue :)
