### ISSUE TITLE
FileUpload forgets tablename

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#327]
When you edit an existing table by `Fileupload`, then `tablename` only persists on the upload step. It will be forgotten on all other steps
`https://dolthub.awsdev.ld-corp.com/repositories/eltragondolt/eltragondolt-test/upload/1664834375051/upload?branchName=main&tableName=doublecheck&spreadsheet=false`

Repo:
-  Visit some table, download it as a csv
- Click the `pencil` icon, then on `File Upload`
- You should see something like the above link with a `tableName`. If you click to any other step then it will be forgotten

**Comment by coffeegoddd** [comment]
also fixed
