### ISSUE TITLE
The `Jobs` tab is highlighted when `Bounties` are showing

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#330]
Jobs are `highlighted` when you select Bounties. The correct info is shown, only the tabs highlight is wrong.

Repo:
- Go to some bounty repo with a `Jobs` tab,
- Click on `Bounties`

Prod: https://www.dolthub.com/repositories/dolthub/us-housing-prices-v2/bounties/default?refName=main
Dev: https://dolthub.awsdev.ld-corp.com/repositories/dolthub/__DOLT__test_bounty/bounties/default?refName=main

<img width="1300" alt="Screen Shot 2022-10-06 at 11 16 11 AM" src="https://user-images.githubusercontent.com/20196357/194388562-b81ff6ad-36ad-4157-91c2-9c30f0ab4961.png">
<img width="1297" alt="Screen Shot 2022-10-06 at 11 16 02 AM" src="https://user-images.githubusercontent.com/20196357/194388568-de2681ee-e4b8-42ac-a95b-39e5f39c2ee3.png">

**Comment by tbantle22** [comment]
I'll take this one
