### ISSUE TITLE
Can't change branch from workspace

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#335]
If I go to a workspace (i.e. https://dolthub.awsdev.ld-corp.com/repositories/newer-org/json-diff-example/workspaces/09291a21-7424-4cee-b93a-84fee21d8d74) and try to change the branch in the left nav, I see that the `refName` param is appended to the url, but the branch in the left nav selector doesn't change

**Comment by ElTragon** [comment]
We are inconsistent with how we handle urls, sometimes we  append `refName=` when the value is undefined.
