### ISSUE TITLE
Need to hard refresh the page to continue to the next step

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#344]
<img width="1289" alt="Screen Shot 2022-10-13 at 2 18 59 PM" src="https://user-images.githubusercontent.com/20196357/195712860-91d8749d-215d-4041-a4a2-72d363cc40b0.png">

Repo
- Create some table with the `speadsheet editor`
- Choose any Branch for step one
- Create the table with `Create spreadsheet` not the upload option
- On the table Step choose some `pk`
<img width="718" alt="Screen Shot 2022-10-13 at 2 23 16 PM" src="https://user-images.githubusercontent.com/20196357/195713457-6ab312bb-adb0-47ab-aaa4-e81f0e2cbcac.png">
- Then return to the `table` step and try to edit some column name.

*This doesn't happen if you don't pick some column(s) as your 'pk`*

**Comment by coffeegoddd** [comment]
should be fixed
