### ISSUE TITLE
Jobs does not update `Status` unless I refresh the page

### ISSUE THREAD

**Issue by ElTragon** [dolthub/dolthub-issues#345]
<img width="1281" alt="Screen Shot 2022-10-13 at 2 32 05 PM" src="https://user-images.githubusercontent.com/20196357/195714878-461e03f5-03b8-4856-baa4-22e1ab983a5f.png">
<img width="1276" alt="Screen Shot 2022-10-13 at 2 31 57 PM" src="https://user-images.githubusercontent.com/20196357/195714887-3df8ca6e-5116-4d1e-9510-162dd6d467e1.png">

To repo create some job, duplicate the page to see if the job completed. The original page will still be `running`

**Comment by liuliu-dev** [comment]
close as it is refreshed now
