### ISSUE TITLE
Searching databases hides forks

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#346]
If I search for my name on the discover page (i.e. https://www.dolthub.com/discover?q=tbantle) I'm seeing a lot less databases than I do when I view the databases on my profile (https://www.dolthub.com/users/tbantle). On the discover page we group forks, so that all forks are grouped under the parent. But if the search term matches the fork child and not the parent (i.e. the owner name) it doesn't show the database in the list

We should maybe not group forks when a search term is present? Or if search hits a fork and not the parent we should show the parent greyed out with the fork as the child? That might be a less near-at-hand solution

**Comment by tbantle22** [comment]
It's nice that the forks are grouped like this if you search for the database name though https://www.dolthub.com/profile/discover?q=us-jails. Need to find an in between option

**Comment by liuliu-dev** [comment]
> It's nice that the forks are grouped like this if you search for the database name though https://www.dolthub.com/profile/discover?q=us-jails. Need to find an in between option

can achieve this by checking the `hide forks in list` option?
