### ISSUE TITLE
Wrong created date for 1+ year old PRs

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#361]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to [here](https://www.dolthub.com/repositories/dolthub/us-schools/pulls?refName=master)
All PRs were created 7 days ago?

Seems to be due to dolt format migration?

**Screenshots**
![image](https://user-images.githubusercontent.com/40151222/200961134-d55f3532-e659-4896-90d5-f38c157d39b5.png)

**Browser info:**
 - Desktop
 - OS/Device: Windows
 - Browser: Chrome

**Comment by liuliu-dev** [comment]
Yes, it's due to migration. When the database migrated, the PRs got recreated.
