### ISSUE TITLE
Somehow I managed to edit someone else's comment

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolthub-issues#375]
**Describe the bug and expected behavior**

Not sure how I got to this point, but I was able to edit someone else's comment (did it entirely accidentally.)

**To Reproduce**
Not sure how to repro.

**Screenshots**
<img width="675" alt="image" src="https://user-images.githubusercontent.com/16236421/203123330-75efa09a-ec65-4dd0-9b68-7020527bb724.png">

I wrote this, not @ericmock.

Link here: https://www.dolthub.com/repositories/onefact/paylesshealth/pulls/224?refName=main

**Browser info:**
 - Mobile
 - macOS Monterey
 - Firefox 107.0

**Comment by liuliu-dev** [comment]
Maybe you edit the pull from the edit button next to the pull title? that's the place where the repo admin would be able to edit pull info like pull title and pull description.
 
![Screen Shot 2022-11-21 at 9 54 05 AM](https://user-images.githubusercontent.com/6688812/203126190-8859ec2b-d33e-456b-b865-5da4a0c9af1f.png)

**Comment by alecstein** [comment]
Oh yea you're right -- I guess the interface changed recently and now descriptions look like comments.
