### ISSUE TITLE
Better API error response

### ISSUE THREAD

**Issue by jigglyjams** [dolthub/dolthub-issues#377]
**Describe the bug and expected behavior**

The dolt API is a very awesome and powerful way to utilize dolt. However, the API appears to always return a `query_execution_status: 'Success'` on POST regardless whether the write query ran properly or not.

GET requests with faulty SQL statements return the correct error messages.

**To Reproduce (please include link if applicable)**
1. Send POST request to a repo with a faulty SQL write query
2. Observe result `query_execution_status: 'Success'`. 

See this [python replit](https://replit.com/@jigglyjams/dolt-api#main.py) as an example. You will need to update `owner`, `repo`, and add an auth token to run the replit

**Screenshots**
The write query sent uses an INSERT statement for schema that does not exist yet the API return success

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/83923290/203496925-bc4c49d9-925a-4774-9e89-822797ad8e24.png">

Thanks! Let me know if you need any other information!

**Comment by tbantle22** [comment]
Hello, thanks for reaching out. The write API for sql queries is asynchronous so it's a little different from our read API. When you run an invalid write query you'll see a "Success" for the async operation being created, and you'll need to hit a second endpoint with that `operation_name` in the original response to see the results. Here's some documentation about this if it's helpful: https://docs.dolthub.com/concepts/dolthub/api#writing. Let me know if you have any more questions

**Comment by jigglyjams** [comment]
That makes sense! Thanks for clarifying 🙏 

I've updated the replit and it does response correctly sorry for the issue!

https://replit.com/@jigglyjams/dolt-api#main.py
