### ISSUE TITLE
UX issue on pull request creation without a valid user session

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolthub-issues#378]
**To Reproduce (please include link if applicable)**
1. Sign out of your DoltHub account.
2. Go to some public DoltHub repo and choose some branches to create a PR. Note that "Create pull request" button is visible and clickable despite user not having a valid session.
3. Click the "Create pull request" button.
4. See error. It says nothing about needing to login, which is confusing. 

**Screenshots**
<img width="1440" alt="Screenshot 2022-11-25 at 17 59 11" src="https://user-images.githubusercontent.com/1080220/203957111-999ac257-0049-4533-9325-ff9d2a0da3d4.png">
<img width="1440" alt="Screenshot 2022-11-25 at 17 59 54" src="https://user-images.githubusercontent.com/1080220/203957181-9af56b2d-5439-45e5-bb7b-c50d523be3db.png">

**Browser info:**
 - Desktop
 - OS/Device: macOS
 - Browser Chrome
 - Version 107.0.5304.110 

It should probably not allow the user to choose branches and click the button without logging in.

**Comment by tbantle22** [comment]
Will look into this. Thanks for the issue

**Comment by tbantle22** [comment]
Deploying a fix for this right now. Thanks for the issue
