### ISSUE TITLE
Download query results as CSV - No quotation marks in fields with commas

### ISSUE THREAD

**Issue by carlosalcampos** [dolthub/dolthub-issues#379]
**Describe the bug and expected behavior**

**To Reproduce (please include link if applicable)**
1. Go to https://www.dolthub.com/repositories/ohdsi-brasil/sigtap_omop
2. Click on Options
3. Click on Download query results as CSV
4. Open the CSV file
5. See the problem: fields with commas are not between quotes. Example: sourceCode = '0401020045'

* Observation: this bug does not occur when you click "Options" -> Download my_table_name as CSV (download the full table)

**Screenshots**
CSV file:
![image](https://user-images.githubusercontent.com/19752452/204572430-1b92c805-a4e7-4172-bd3d-e2798c047aa7.png)

**Browser info:**
 - Desktop
 - OS/Device: Windows 10 Home Single Language
 - Browser: Chrome
 - Version 107.0.5304.107 64 bits

**Additional context**
-

**Comment by carlosalcampos** [comment]
@tbantle22 ,
Was this bug solved?

**Comment by tbantle22** [comment]
The fix is being deployed right now!

**Comment by tbantle22** [comment]
Should work now. Let me know if you see differently

**Comment by carlosalcampos** [comment]
Great!
I tested it and the problem was solved!
Thanks @tbantle22 !!!

**Comment by tbantle22** [comment]
Awesome! Thanks for filing an issue and letting us know
