### ISSUE TITLE
Create Filter - Issues Page on Dolthub

### ISSUE THREAD

**Issue by carlosalcampos** [dolthub/dolthub-issues#380]
**Is your feature request related to a problem? Please describe.**
I can not filter issues by State (Open, Closed)
![image](https://user-images.githubusercontent.com/19752452/204614425-443ecace-518f-4800-afbc-83086e16d29e.png)

**Describe the solution you'd like**
I would like a filter similiar that we have in "Pull request" page
![image](https://user-images.githubusercontent.com/19752452/204614584-28deae91-6bff-4802-9390-8ac0cc2c0447.png)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by carlosalcampos** [comment]
Very happy with the new feature!
Thanks @liuliu-dev !

**Comment by liuliu-dev** [comment]
> Very happy with the new feature! Thanks @liuliu-dev !

Great! Thanks for the feature request :)
