### ISSUE TITLE
Clone and Add buttons missing.

### ISSUE THREAD

**Issue by ericmock** [dolthub/dolthub-issues#383]
When you shrink the window, the Clone and Add buttons disappear, and there appears to be no way to access them.

**Screenshots**

**Browser info:**
 - Desktop
 - Linux/Manjaro
 - Chrome
 - 108.0.5359.71

![image](https://user-images.githubusercontent.com/25640/205503652-7a3f4a63-078c-48b0-a098-b55e15386811.png)
![image](https://user-images.githubusercontent.com/25640/205503683-edbdd47d-e3de-4b32-8976-1b4a8ec108b9.png)

**Comment by tbantle22** [comment]
Deploying a fix for this right now. Thanks for the issue

**Comment by ericmock** [comment]
Excellent.  Glad to help.
