### ISSUE TITLE
SQL API shows value is not primary key when it is

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolthub-issues#387]
**Describe the bug and expected behavior**

SQL API shows that a value is not a primary key when it actually is. `dolt schema show` gives

<img width="510" alt="image" src="https://user-images.githubusercontent.com/16236421/206568234-1e4cb6fc-5184-42aa-bc99-c3d0ad4e6c93.png">

notice how CCN is a primary key. 

**To Reproduce**
1. Go to https://www.dolthub.com/repositories/onefact/paylesshealth/data/main
2. Click on SQL API
3. Scroll down to `schema`
4. See error (shouldn't `isPrimaryKey` be True?)

**Screenshots**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16236421/206567920-b548cd2a-ad2c-46a9-b3b5-563cfe42d22e.png">

**Browser info:**
 - Firefox Desktop, macOS

**Comment by druvv** [comment]
Query results never have primary keys. We shouldn't include the `isPrimaryKey` json column in the API response.
