### ISSUE TITLE
Custom commit messages in DoltHub UI

### ISSUE THREAD

**Issue by aarreedd** [dolthub/dolthub-issues#388]
When making commits from the UI there is no option to set you own commit message. Commit message defaults to e.g. "table updated with data from data.csv".

I would like to be able to set a more descriptive commit message from the UI.

**Comment by aarreedd** [comment]
Ideally there would be a way to set the commit message when merging from the UI.

**Comment by liuliu-dev** [comment]
@aarreedd thanks for the feature request! I would work on setting a custom commit message when updating a table with file upload.

Also, we have a feature request about [squashing workspace commits ](https://github.com/dolthub/dolthub-issues/issues/381) , when that feature is out, I would work on setting a custom commit message in workspaces.

**Comment by aarreedd** [comment]
Great to see this get added. I think you are right that squashing all commits in a branch from the UI before merging is super important as well.

**Comment by liuliu-dev** [comment]
> Great to see this get added. I think you are right that squashing all commits in a branch from the UI before merging is super important as well.

Thank you for the feature request :)
