### ISSUE TITLE
Visual commit graph across branches

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolthub-issues#391]
Many Git tools provide a visualization of the commit graph across branches ([example](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F65855361%2Fgit-log-graph-differs-in-intellij-and-vscode&psig=AOvVaw1s2Q5fzsnlgZJ2nUt1LAPn&ust=1671658868989000&source=images&cd=vfe&ved=2ahUKEwjE9OvZlIn8AhXsFzQIHeraAOEQjRx6BAgAEAo)). 

It would be cool to see the same sort of branch visualization for a Dolt database on DoltHub.

**Comment by liuliu-dev** [comment]
Thanks for the feature request, would be a fun project to work on!

**Comment by liuliu-dev** [comment]
this is in production: 
https://www.dolthub.com/repositories/dolthub/hospital-prices-allpayers/commits/main/graph

**Comment by fulghum** [comment]
Whoohooo! Nice work @liuliu-dev! 🙌
