### ISSUE TITLE
Create DoltHub database repo via API rquest

### ISSUE THREAD

**Issue by noamross** [dolthub/dolthub-issues#394]
**Is your feature request related to a problem? Please describe.**
I'd like less overhead in setting up a new Dolt project.

**Describe the solution you'd like**
I'd like to be able to make a REST (or GraphQL) request to create a new dolt repo, so when setting up a new project locally I could script creating the new repo, setting the remote, and pushing to the remote. 

**Describe alternatives you've considered**
It's possible this exists in the GraphQL API already but is undocumented. 

**Additional context**
This is related to #1 , #245, and #304, all of which are asking for REST endpoints to automate processes in the DoltHub web interface.

**Comment by liuliu-dev** [comment]
Hi @noamross, I wanted to let you know that we have created a new database API and have also added some pull request APIs. You can find more information about them in our documentation here: https://docs.dolthub.com/guides/dolthub-api/database 
Thanks for the request :)
