### ISSUE TITLE
Database size in postgres after migration may be larger than what's stored in s3

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#398]
DoltHub migration copies the old database (repository size) over to the new database during migration. This leads to migrated databases reflecting sizes larger than what's actually in their s3 folder, which is a bit weird, and might cause some confusion down the line. Discussed this morning with @druvv who has a proposed fix.

**Comment by druvv** [comment]
Fixed in https://github.com/dolthub/ld/pull/12519
