### ISSUE TITLE
File import never finishes but cloning a fork of the database has tables

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#399]
Steps to repro:

1. Create a new database on dolthub
2. click file upload
3. Upload [dolt_20230103_2015EST.sql.txt](https://github.com/dolthub/dolthub-issues/files/10340851/dolt_20230103_2015EST.sql.txt)
4. Job never finishes https://www.dolthub.com/repositories/timsehn/show_off_import/jobs?refName=main
5. Database is empty when you clone
6. But if you fork and clone, the tables are there.

**Comment by coffeegoddd** [comment]
The reason the job never completed was due to an infinite loop in the sql file insert counting code. This is now fixed.
The populated data in the fork is unrelated to file import, I suspect the user added data and pushed manually before the fork was successfully created.
