### ISSUE TITLE
Editable workspace names

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#401]
A customer likes the new automated workspace names but would like the ability to edit them.

**Comment by taliakustin** [comment]
Thanks for that Liu Liu, can you please elaborate on where I can edit the workspace names from?

**Comment by liuliu-dev** [comment]
> Thanks for that Liu Liu, can you please elaborate on where I can edit the workspace names from?

Sure. It's the branch names created for a pull request that would be editable:
In the workspace, click create a pull request, and this modal will pop up with branch name input:

![213044762-4d748a08-68f2-4b66-b8c0-ce5ffbfa8b5c](https://user-images.githubusercontent.com/6688812/213935935-a8befd53-b93e-434f-9a43-1866f27a1c3c.png)

Do you also want workspace names to be editable?

**Comment by taliakustin** [comment]
Im trying to upload a new file and I do not come across something that resembles the screenshot. 
What am I doing wrong?

**Comment by liuliu-dev** [comment]
@taliakustin you are not doing it wrong. The changes were added to workspaces, if you are editing data using queries, that screenshot will show up. 

I created an issue for editing import job branch names, you can follow it here:
https://github.com/dolthub/dolthub-issues/issues/407

I will get it out soon :)

**Comment by taliakustin** [comment]
Thanks!

**Comment by liuliu-dev** [comment]
Hi @taliakustin ,  you can now edit the branch name when uploading a file:
![Screen Shot 2023-01-23 at 3 26 12 PM](https://user-images.githubusercontent.com/6688812/214175391-894e1469-e535-42af-9b7d-225da51080bd.png)
