### ISSUE TITLE
Dolthub webhook payload with empty head value

### ISSUE THREAD

**Issue by taliakustin** [dolthub/dolthub-issues#413]
Hi
I am getting an empty head value in my webhook and I understand that this isn't ok
This is the payload:

{
  "ref": "refs/heads/in_agg",
  "head": "",
  "prev": "bu4q0huhu1ja9sl4mlb4p7tifpujtssj",
  "repository": {
    "name": "Hadassah",
    "owner": "briya"
  }
}
AttempID: 5a4e3ba0-135f-452a-91a6-be0d065240ab

THanks!

**Comment by timsehn** [comment]
Moving to dolthub-issues and assigning to @liuliu-dev

**Comment by timsehn** [comment]
Finally got a repro here :-)

**Comment by liuliu-dev** [comment]
I checked the database, looks like that branch `in_agg` is deleted. When a branch gets deleted and the commit is pushed, it will send a payload with an empty head, I guess this payload looks correct?

**Comment by taliakustin** [comment]
Oh I see - so when a branch is deleted it will send a payload with an empty head?

**Comment by liuliu-dev** [comment]
> Oh I see - so when a branch is deleted it will send a payload with an empty head?

Correct. When you have **push** webhook applied, the payload will have the information of the previous commit hash and the head commit hash. Deleting a branch will send you a payload with an empty head, and creating a new branch will send you a payload with an empty previous commit hash.

I'm working on adding a webhook on branches, which will give you more readable information when a branch gets deleted or created. The payload will look like this:

```
{
"branch": "branchName",
"repository": {
"name": "repositoryName",
"owner": "ownerName"
}
"action": "created branch"/"deleted branch"
}
```

**Comment by liuliu-dev** [comment]
@taliakustin webhook on branch creation/deletion is live :)
