### ISSUE TITLE
delete branch user is not in pull log info

### ISSUE THREAD

**Issue by liuliu-dev** [dolthub/dolthub-issues#414]
![Screen Shot 2023-02-09 at 9 50 15 AM](https://user-images.githubusercontent.com/6688812/217896619-bfcafd1e-928f-4ab6-b19a-9c271c42654a.png)

**Comment by liuliu-dev** [comment]
problem:
when deleting a branch in dolthubapi, it calls `ddb.DeleteBranch(ctx, branchRef)` in dolt, which does not pass the callingUser info, then when the commit is pushed, in internalRepository service, callingUser would be nil : `unitOfWork.Pull().UpdatePull(ctx, &updated, **nil**, true, to.Owner+"/"+to.Repo, from.DB, to.DB, updated.PremergeFromCommit, updated.PremergeToCommit)`

 possible solution:
adding branch activity log? this might also solve https://github.com/dolthub/dolthub-issues/issues/408

**Comment by tbantle22** [comment]
This is duplicate of https://github.com/dolthub/dolthub-issues/issues/18

**Comment by liuliu-dev** [comment]
i see, closing this one as duplicate
