### ISSUE TITLE
Dolthub API down?

### ISSUE THREAD

**Issue by radao** [dolthub/dolthub-issues#421]
**Describe the bug and expected behavior**

Hello,

Today I've been getting periodic errors loading data from DoltHub. In `doltcli`, the error I'm seeing is:
```bash
doltcli.dolt.DoltException: ('pull origin main', '', "unable to find 'main' on 'origin'; rpc error: code = Internal desc = Could not get chunkstore\n", 1)
```
This is occuring on multiple methods that make calls to DoltHub.

Additionally, I'm seeing this in the UI for most repos:
<img width="327" alt="Screen Shot 2023-02-16 at 16 26 38" src="https://user-images.githubusercontent.com/2007531/219410708-f7ad65b5-e28a-4540-b63b-24917bd731bd.png">

Not sure if this is a temporary outage for everyone or something on my side.

**To Reproduce (please include link if applicable)**

**Screenshots**

**Browser info:**
 - Mobile or desktop
 - OS/Device: [e.g. iOS]

**Additional context**

**Comment by liuliu-dev** [comment]
Thanks for reporting the issue, we are investigating it.

**Comment by timsehn** [comment]
This may be related to the broader outage we were experiencing at the time.

**Comment by radao** [comment]
Looks like the issue was resolved as of this morning, closing.
