### ISSUE TITLE
Ability to modify the schema of a CSV upload

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolthub-issues#422]
The user wants the ability to rename or ignore columns in a CSV upload.

**Comment by timsehn** [comment]
So, after doing some testing with @liuliu-dev, you can edit the schema of an import on the Pull Request diff. You can now drop a column. Maybe we add rename column there and call it done?

**Comment by timsehn** [comment]
After discussing with the customer, he is looking for an option with existing tables to modify the import by either renaming or dropping columns. TablePlus CSV import has a good example.

**Comment by timsehn** [comment]
From @liuliu-dev and I playing, this is the screen we want to stick in between CSV file upload and the commit message if there is an existing table they are importing the CSV onto.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/5376236/225754342-e96ba734-8d28-4e51-9dce-7f666da4f12e.png">

This allows users to map column names to the current schema, and choose which columns to import.

I'm not sure if this should be there for new tables. Need to think more once we have it implemented :-)

**Comment by tbantle22** [comment]
We used to have an edit schema form during file upload that looked like that. Could probably modify it pretty easily to have it drop a column also?
![upload-edit-schema](https://user-images.githubusercontent.com/29443194/226050099-bd5bc0d2-4878-46ee-b5de-5a90813d68e1.png)
