### ISSUE TITLE
DoltHub API Additions

### ISSUE THREAD

**Issue by databytes64** [dolthub/dolthub-issues#423]
**Is your feature request related to a problem? Please describe.**
I use the GraphQL endpoints to perform tasks which are not currently solved by the DoltHub API.

**Describe the solution you'd like**
I think you should add API functionality for the following:
- delete pr
- delete branch (with associated PR)
- get all PRs for a repo
- get diff info on a specific table for a specific PR (the actual row diffs. I don't know if they currently cap out somewhere or not with GraphQL, but following the same behavior should be fine)

**Describe alternatives you've considered**
Directly using the GraphQL endpoints seem fine, but happy to use an alternative that more people are familiar with.

**Comment by tbantle22** [comment]
By delete PR do you mean close PR? DoltHub doesn't support deleting PRs

**Comment by databytes64** [comment]
Yes, close PR, sorry. However, PRs can indeed be deleted, just delete the database and BAM they're gone 🤣
