### ISSUE TITLE
"Create Branch" api endpoint needed

### ISSUE THREAD

**Issue by pirimoglu** [dolthub/dolthub-issues#427]
**Is your feature request related to a problem? Please describe.**
I'm trying to create dolt branch from my automation app. I couldn't find a solution.

**Describe the solution you'd like**
Add a api endpoint, that create branch. This endpoint gets parent branch and new branch names.

**Comment by liuliu-dev** [comment]
Hi @pirimoglu , the create branch API endpoint is now available. You can find the documentation for it here: https://docs.dolthub.com/products/dolthub/dolthub-api/database#owner-database-branches

Closing the issue as completed. Thank you for the feature request!
