### ISSUE TITLE
Dolthub backend down

### ISSUE THREAD

**Issue by radao** [dolthub/dolthub-issues#456]
**Describe the bug and expected behavior**

Can't sign in and all databases/organizations are gone. Maybe related to 1.0 release? 🤔 

**To Reproduce (please include link if applicable)**
1. Go to dolthub.com

**Screenshots**
<img width="963" alt="Screen Shot 2023-05-06 at 10 49 04" src="https://user-images.githubusercontent.com/2007531/236613858-13c25dfc-c861-4ae5-b5a8-af870245b19f.png">
<img width="1025" alt="Screen Shot 2023-05-06 at 10 52 12" src="https://user-images.githubusercontent.com/2007531/236613987-4f66d7f1-dad9-40e5-8591-dbfb031033cf.png">

**Browser info:**
 - Mobile or desktop: desktop
 - OS/Device: Macbook Pro
 - Browser: Chrome
 - Version: 112.0.5615.137

**Additional context**

**Comment by timsehn** [comment]
I think this was due to a backend migration we were doing last night. Sorry for the inconvenienece.
