### ISSUE TITLE
Potential page load performance degradation

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#466]
DoltHub cypress tests have been failing consistently for two days on different tests. It seems like most commonly the /discover page and a merged pull page due to the content not loading in time

https://github.com/dolthub/dolthub-cypress/actions

**Comment by liuliu-dev** [comment]
pulled the diagram from last 2 days for the `repo list`, `pull`, and `diff` queries:
https://prometheus.awsprod.ld-corp.com/graph?g0.expr=histogram_quantile(0.5%2C%20sum(rate(dbr_query_latency_bucket%7Bdatabase_type%3D%22postgres%22%2Cquery_id%3D~%22%5E(pull%7Crepository_repo_list).*%7C.*diff.*%22%7D%5B3m%5D))%20by%20(query_id%2C%20le))&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2d&g1.expr=histogram_quantile(0.5%2C%20sum(rate(dbr_query_latency_bucket%7Bdatabase_type%3D%22dolt%22%2Cquery_id%3D~%22%5E(pull%7Crepository_repo_list).*%7C.*diff.*%22%7D%5B3m%5D))%20by%20(query_id%2C%20le))&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=2d&g1.end_input=2023-05-23%2016%3A37%3A38&g1.moment_input=2023-05-23%2016%3A37%3A38
