### ISSUE TITLE
Pull request title should be editable

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolthub-issues#472]
Now it is possible to edit description of pull request I authored, but not the title. Sometimes I want to do that when I update the contents of data submission.

**Comment by liuliu-dev** [comment]
You should be able to edit the title if you have written permission on the database.
Is there an `edit` button next to your pull request's title?

<img width="816" alt="Screenshot 2023-06-12 at 9 26 51 AM" src="https://github.com/dolthub/dolthub-issues/assets/6688812/e766684b-90c9-456c-8774-3406c030487d">

**Comment by rl1987** [comment]
No. I want to edit the title as bounty participant.

![Screenshot 2023-06-12 at 19 31 14](https://github.com/dolthub/dolthub-issues/assets/1080220/185ca95a-e0b6-4a80-be6b-c2d49714cd9a)

**Comment by liuliu-dev** [comment]
I see now, will fix it.

**Comment by liuliu-dev** [comment]
@rl1987 should be able to edit the title now.
