### ISSUE TITLE
Need Search Button

### ISSUE THREAD

**Issue by subhra78** [dolthub/dolthub-issues#475]
Hi, could you please add search button on spreadsheet editor? 
At this moment if I go to Spreadsheet Editor from the table, I need to scroll down and identify  the row manually. It would be great if there is an search button so that someone can pull the desire row based on search result like id or any other values. 

Thank you.

**Comment by LaPingvino** [comment]
(Probably good for this to copy the design language from Excel etc, where you can pick from a list of options used or give your own value per column...)

**Comment by liuliu-dev** [comment]
We've added column filters in spreadsheet editor, currently, these filters are available for varchar, text, and numeric data types, we will support more data types in the future.
![Screenshot 2023-08-23 at 1 40 20 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/8f92db55-a5ae-49f0-8221-c4a2b973960b)

**Comment by liuliu-dev** [comment]
closing this as completed.
made another issue for supporting more data types: https://github.com/dolthub/dolthub-issues/issues/494

**Comment by subhra78** [comment]
Thank you @liuliu-dev for adding this , this is really helpful.

**Comment by liuliu-dev** [comment]
> Thank you @liuliu-dev for adding this , this is really helpful.

No problem, thanks for the feature request :)
