### ISSUE TITLE
Cannot create a table in new database using spreadsheet editor

### ISSUE THREAD

**Issue by jon-mellon** [dolthub/dolthub-issues#478]
Intended behavior: create new table in database using spreadsheet editor
Actual behavior: next button is grayed out on file importer making the creation impossible

In new repository:
* I click Spreadsheet editor
* choose option "create new table" and enter table name "test"
* click next
* enter column names variable and value on spreadsheet editor and add 2 test rows with numbers
* click upload table
* Next button is grayed out and unclickable
* try the rename columns option
* next button is still grayed out

**Browser info:**
 - desktop
 - windows 11
 - tried in edge and chrome

**Comment by liuliu-dev** [comment]
Thanks for reporting the issue, we will fix it soon.

**Comment by liuliu-dev** [comment]
Hi @jon-mellon , this should be fixed now, thanks for reporting the issue :)
