### ISSUE TITLE
"Prevent deletions" branch protection option doesn't prevent deletion from merged PR page

### ISSUE THREAD

**Issue by prodoelmit** [dolthub/dolthub-issues#483]
**Describe the bug and expected behavior**

* Set branch `develop` as protected with "Prevent deletions" mark
* Create PR from `develop` to `release`, merge it 
* Expected: On PR page there is no "Wanna delete this branch?" block
* Real: There is this block, and clicking "Delete" really deletes branch

**Video**
https://drive.google.com/file/d/1oKZXHXVnBAP5C3AlAyg7iwBygEU50_D6/view?usp=sharing (I need your e-mail to give access)

**Comment by liuliu-dev** [comment]
Hi @prodoelmit , my email is liu@dolthub.com, could you give me access to the video?

**Comment by prodoelmit** [comment]
@liuliu-dev done

**Comment by liuliu-dev** [comment]
close as admins are allowed to delete a protected branch.
