### ISSUE TITLE
Ability to set branch protection for multiple branches matching pattern

### ISSUE THREAD

**Issue by prodoelmit** [dolthub/dolthub-issues#484]
**Is your feature request related to a problem? Please describe.**
We have flow very similar to git-flow. That causes us to have different `release` branch for every release. All those branches need branch protection so that there are no unapproved PRs 

**Describe the solution you'd like**
Add option to specify name pattern instead of exact match. E.g. there is such option in gitlab: [docs](https://github.com/dolthub/dolthub-issues/issues/483)

**Describe alternatives you've considered**
This could be done via webhook + API if you had branch protection settings exposed

**Comment by liuliu-dev** [comment]
Hi @prodoelmit , this feature is out, you can add a name pattern specify with [fnmatch syntax](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch).

<img width="804" alt="Screenshot 2024-04-17 at 9 13 51 AM" src="https://github.com/dolthub/dolthub-issues/assets/6688812/d1217e79-1718-47c9-a0bb-eb853e86a585">

Thanks for the feature request :)
