### ISSUE TITLE
Two-Factor Authentication (2FA)

### ISSUE THREAD

**Issue by fp1tech** [dolthub/dolthub-issues#487]
Our company requires 2FA on all of our services. While we can use Github's 2FA on our accounts it would better if we could force it from DoltHub and use our domain emails for the accounts.

Would like support for apps like Google Auth, Authy, etc and backup codes.

**Comment by reltuk** [comment]
Hi @fp1tech, thanks for the great feature request.

We went to scope this, and the nearest at hand solution for 2FA on dolthub.com is a one-time-use code which is sent via email when the user logs in. So it's just a binary setting on the user account whether we send and require that code on signin or not.

We can also scope adding support for TOTP devices, as well as recover codes, etc. But we wanted to know: does the one time use code sent via email at login meet your organization's 2FA requirements here. Or do you require something deeper 
like support for a virtual MFA device?

Regardless of your answer, eventually we would obviously love to support 2FA TOTP devices, as well as other forms of 2FA.

**Comment by bpf120** [comment]
Hi @fp1tech  Thank you for checking out Dolt and DoltHub. We'd love to learn about your use case too. You can [email me](mailto:brianf@dolthub.com) or come by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to share.

**Comment by liuliu-dev** [comment]
Hi @fp1tech , 2FA is available now. To set it up:

1. Sign in to your account.

2. Navigate to the security settings section. Enable 2FA by visiting this link: https://www.dolthub.com/settings/security.
<img width="1033" alt="Screenshot 2023-09-05 at 10 39 06 AM" src="https://github.com/dolthub/dolthub-issues/assets/6688812/6e589c01-8eb0-4312-9551-e9eb90f5eeb4">

3. After enabling 2FA, you will receive an email containing a verification code. Use this code to complete the sign-in process.
<img width="1074" alt="Screenshot 2023-09-05 at 10 39 18 AM" src="https://github.com/dolthub/dolthub-issues/assets/6688812/030546e4-7829-4555-84ef-e47cda01ad5d">
