### ISSUE TITLE
Several operations create error about 255 character limit

### ISSUE THREAD

**Issue by LaPingvino** [dolthub/dolthub-issues#489]
Example situations where I hit this: creating and saving a saved query, editing fields in a select overview, I think some more places. I suspect this might have been entered recently, because I haven't seen it before, maybe something with the fix for the schema changes bug?

**Comment by liuliu-dev** [comment]
Thanks for the report, we are looking into it today.

**Comment by liuliu-dev** [comment]
close as fixed.
