### ISSUE TITLE
remove query row limit for csv download

### ISSUE THREAD

**Issue by g-sando** [dolthub/dolthub-issues#495]
Currently only 200 rows are returned for any executed query other than the default table queries, which means only 200 rows can be exported to csv without using dolt in the command line. This export of a View/Saved Query or API call is the main and most basic functionality that allows users in our org who aren't devs to access our data autonomously. 

Request: Remove the query output limit to allow full query and API call downloads to csv.

**Describe alternatives you've considered**
Using the CLI. The need for this makes the end-to-end user-friendliness for users who aren't familiar with the CLI very low.

![image](https://github.com/dolthub/dolthub-issues/assets/124654500/3d447239-c343-4573-81e1-d1156f23b8ac)

**Comment by timsehn** [comment]
As a workaround, you can have the user download the full CSV for the table and perform whatever filters they need on the full table.

The problem on our side is that the query can take more time than a reasonable webpage load if we remove the row limits. We can't stream the results like a full table.

Good feature request though. I definitely wish there was a better way here as well.

**Comment by liuliu-dev** [comment]
Hi @g-sando, thanks for the feature request. 
The nearest at hand solution for this would be increase the row limit, potentially setting it to 1000, would that be enough for you? Or we can create a job and support unlimited downloads, however, this will take more time to implement. 
Which approach suits better with your needs?

**Comment by g-sando** [comment]
Hi @liuliu-dev sorry for the delay, increasing to 1000 for now would still be great and still increase our flexibility by a lot, thanks so much. 

Unlimited would be ideal long-term but I understand the constraints Tim mentioned so can circle back if that becomes unavoidable down the line!

**Comment by liuliu-dev** [comment]
@g-sando I've increased the row limit to 1000. If you have any further questions or requests, feel free to reach out. Thanks for your understanding!

![Screenshot 2023-09-07 at 10 49 00 AM](https://github.com/dolthub/dolthub-issues/assets/6688812/12461130-7f3c-44e2-a2c5-cafaad18bcf9)

**Comment by liuliu-dev** [comment]
Hi @g-sando , now you can create a query job and have unlimited downloads! You can find the 'Create Query Job' button in the SQL editor here:
![Screenshot 2023-12-11 at 12 52 51 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/e093485e-671e-4083-b792-c9df6c85d4fd)

Once the job is done, you'll find a download link for the result on the job page:
![Screenshot 2023-12-11 at 12 56 52 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/d155cbbd-abd9-4bf1-8f43-b91076e47b2f)

I will close this issue as completed :)
