### ISSUE TITLE
Allow users to request edit access to a database

### ISSUE THREAD

**Issue by jon-mellon** [dolthub/dolthub-issues#504]
A use case for dolthub is for members of the public to contribute to a shared data resource. The data editing functionality is much easier for users who are members of the project compared to the forking and pull request workflow that is available to non-members.

It would be useful if there was an option to enable:
1) a place for users to request membership (along with an explanation)
2) the ability to give automatic membership to users (subject to branch protections)

**Comment by timsehn** [comment]
This is a DoltHub issue.

**Comment by timsehn** [comment]
Here is a mock UI.

<img width="1289" alt="Screenshot 2023-10-09 at 1 03 21 PM" src="https://github.com/dolthub/dolthub-issues/assets/5376236/8e3406c3-2cd9-4c5e-91dc-d1fe3952dc52">

**Comment by liuliu-dev** [comment]
Hi @jon-mellon, you are now able to submit a request for write access to a database

![Screenshot 2024-02-05 at 4 47 06 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/5b2cb866-9238-4504-ae1e-6e62068658b9)

After submitting your request, an email notification will be sent to the database owner, and you will be notified via email when your request is approved or rejected.

Thanks for the feature request :)

**Comment by liuliu-dev** [comment]
Hi @jon-mellon , I just moved the button to the left side , in the database permissions label,  just in case you're looking for it and can't find it.
![Screenshot 2024-02-09 at 1 45 34 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/925555ba-5a89-4697-8109-ccd27d0ce32b)
