### ISSUE TITLE
Send `secret` with webhook payload so client can authenticate events

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#506]
basically for dolthub webhooks, when a user creates a webhook endpoint, they also add a secret (which we store in the db)
but we never send that secret on any of the webhook payloads
so the client can never verify that the events are truly coming from dolthub

**Comment by coffeegoddd** [comment]
A stretch goal at a later time is to do what github does as documented here: https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries

**Comment by liuliu-dev** [comment]
the service change is in, will close it after the front end change is out
