### ISSUE TITLE
Upgrade (or replace) react-data-grid

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#509]
`react-data-grid` does not work with Next.js v13.5.4 and above due to [this issue](https://github.com/vercel/next.js/issues/56480). It looks like `react-data-grid` has a [fix in source](https://github.com/adazzle/react-data-grid/pull/3356), but there are a lot of changes required to migrate to the newest version. We need to either figure out how to upgrade to the latest `react-data-grid` version or use a different package for the spreadsheet editor

**Comment by liuliu-dev** [comment]
completed
