### ISSUE TITLE
support multistatements in dolthub write API

### ISSUE THREAD

**Issue by jon-mellon** [dolthub/dolthub-issues#510]
I would like to be able to send multiline SQL statements to the write API. Given the rate limits of the write API, it would be useful to be able to better bundle requests. When adding many rows to a single table, this can be done reasonably easily. However, some of my user request handling requires updates to multiple tables which would ideally be able to be done in a single API request rather than having to invoke a separate API call and polling workflow for the changes to each table. 

As an example, it would be useful to be able to pass this combined set of SQL queries to the write API in one go:

```
CREATE TABLE test1 (
  id CHAR(36) default(UUID()),
  PRIMARY KEY (id)
);
CREATE TABLE test2 (
  id CHAR(36) default(UUID()),
  PRIMARY KEY (id)
);
```

**Comment by liuliu-dev** [comment]
Hi @jon-mellon , to execute multiple queries on the database, you can use the [upload api](https://docs.dolthub.com/products/dolthub/api/database#owner-database-upload), put all the queries in an SQL file and send it to this api endpoint.
