### ISSUE TITLE
Can't upload any csv to a db

### ISSUE THREAD

**Issue by IraMelamud** [dolthub/dolthub-issues#517]
Hello,
I work at Briya, and we use doltHub.
When trying to upload csv files to db Asuta_ashdod, the process gets stuck on status "pending" for days. 
Without showing an error.
I create new branch from Main branch, try to upload csv file to edit Mapping existing file, the transition from stage to stage takes a lot of time, and at the end- it get stuck on "pending". I'm unable to upload my file to temporary branch. I don't know if the problem exists when trying to merge new branch to Main.
I tried to upload to main branch and to sub branch- same result. Tried to upload to different DB (Briya/playground)- same result.
Initially, I created the db Assuta-ashdod. I was able to upload files to it previously. Last time it worked was pull request 26#. 
I don't know if it's the same bug, but this is error I received before this issue started:
creation of job failed after 5 retries: final error: rpc error: code = NotFound desc = branch not found: MedAdmin_3_and_fake
 
**Screenshots**
<img width="1012" alt="Screen Shot 2023-12-02 at 11 22 12" src="https://github.com/dolthub/dolthub-issues/assets/139692882/1a925c90-c0ee-46d4-bc97-4301b01289fb">

**Browser info:**
 - Mobile
 - Mac OS
 - Browser- chrome
<img width="1012" alt="Screen Shot 2023-12-02 at 11 25 14" src="https://github.com/dolthub/dolthub-issues/assets/139692882/bf11e1ce-0a38-4f6e-a27d-1af9f6ae010b">

**Additional context**

**Comment by IraMelamud** [comment]
I tried to upload to another DB of ours- it's not working as well. Not just to Assuta Ashdod db. 
In addition, every transition from one screen to another- is taking a lot of time.

**Comment by coffeegoddd** [comment]
We tracked down the uploading failures to a bug in a recent dependency upgrade we made. After making another upgrade with the fix for the bug, uploading on DoltHub is working again.

**Comment by coffeegoddd** [comment]
We tracked down this issue to a bug in DoltHub's Job scheduler. The fix is in production, closing.
