### ISSUE TITLE
Include a download link for the import job, allowing the downloaded file to be modified and reimported

### ISSUE THREAD

**Issue by IraMelamud** [dolthub/dolthub-issues#519]
Current status: 
When uploading a file in jobs/PR section, and getting comments to change things, you need to re-create the csv file, do the changes needed and re upload the file, while connecting it to a temp branch. additionally, no other teammate can resolve the task, due to not having the original file that was uploaded to a certain job in Dolt.
Purpose: 
Improve user experience, making it easier and faster to resolve comments in PRs. Allowing different teammates to have access to file in progress.
Posible solution:
When having csv file in jobs section, to have the ability to download it from jobs, make all needed changes and re-upload again,
a- to same branch 
b- to temp branch and then to merge them.
It will make UX much better and will allow few different teammates to work on same project.
<img width="1009" alt="Screen Shot 2023-12-05 at 21 35 37" src="https://github.com/dolthub/dolthub-issues/assets/139692882/a70ca9a0-8b3d-4f78-9b47-b7112e3f5697">

**Comment by liuliu-dev** [comment]
After further consideration, I believe a more effective approach would be to directly modify the table within the import/pull request branch.

In the screenshot you provided, the branch `JOINS_ira` is created during the CSV file import. To modify the data in this file, you can directly work on this branch using the following steps:

Click on the branch name JOINS_ira on this pull request page, which will navigate you to the database on this branch.

Once on the database page, you have several options for modifying the table:

1. Use the cell dropdown menu:
![Screenshot 2023-12-05 at 12 06 49 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/cab4682e-0693-466a-a552-4bd4e8708be2)

2. Use the SQL editor:
![Screenshot 2023-12-05 at 12 09 06 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/94a1a1b0-24a7-4e44-8a56-4ff6e43d35ce)

Using either the cell dropdown or SQL editor, a workspace will be created. From there, select `commit directly`, and the changes will be applied directly to the chosen branch `JOINS_ira`.

You can also use the spreadsheet editor on DoltHub to modify your table:
- Click the pencil icon next to the table name
![Screenshot 2023-12-05 at 12 11 47 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/3952d667-ea0a-402d-a348-c3d157bcaadf)

- Select the spreadsheet editor to change the data:
![Screenshot 2023-12-05 at 12 12 34 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/8b79abe1-98bd-4ed9-8daa-9b4002519ab9)

Note that the spreadsheet method will create a new branch based on `JOINS_ira`.
Let me know if you have any question:)
