### ISSUE TITLE
Increasing the number of characters in pr comments

### ISSUE THREAD

**Issue by IraMelamud** [dolthub/dolthub-issues#520]
**Describe the bug and expected behavior**
When writing comments in PR [pull requests] there is limit of length. Please make it bigger, So more characters can be inserted.
When I receive pr with lots of comments from the reviewer - I want to duplicate them and answer per question. In current status - it is not possible and I have to write the answers separately from the questions. Inconvenient to write or to read afterwards
 
**Screenshots**
<img width="768" alt="Screen Shot 2023-12-10 at 11 35 25" src="https://github.com/dolthub/dolthub-issues/assets/139692882/49f8c4c8-d5d3-451c-8986-e59f0f7e68ea">

**Browser info:**
 - Mobile or desktop - neither
 https://www.dolthub.com/repositories/briya
 - OS/Device:Mac os
 - Browser- chrome 

**Additional context**

**Comment by liuliu-dev** [comment]
Hi @IraMelamud , the char number limit has been increased to 10,000.
