### ISSUE TITLE
[dolthub]: unable to save query

### ISSUE THREAD

**Issue by ShaunSHamilton** [dolthub/dolthub-issues#538]
1. Create query in "query bar"
2. Click "save"
3. Modal pops up to give name/description to query
4. Add name/description
5. Click "save"
6. Nothing happens

There are no errors in the console, and the only events in the network tab is the `/api/config` and `https://event.syftdata.com/events` requests.

The query works in the "tables" view. Clicking "cancel" closes the modal, and there are no queries in the "queries" tab.

I am admin of the database.

<details>
  <summary>Image</summary>

![image](https://github.com/dolthub/dolt/assets/51722130/9e46e552-1864-4f58-b72e-291e72503c78)

![image](https://github.com/dolthub/dolt/assets/51722130/833ecc05-d5ea-4440-b14f-1715abe522ec)

</details>

**Comment by timsehn** [comment]
Moving this to dolthub-issues

**Comment by tbantle22** [comment]
Fixing this now. This looks like a bug in the modal changes I shipped yesterday

**Comment by tbantle22** [comment]
This should work now if you try again. Sorry about that
