### ISSUE TITLE
pr invalid commit hash provided

### ISSUE THREAD

**Issue by ShaunSHamilton** [dolthub/dolthub-issues#540]
1) Team member opens PR: https://www.dolthub.com/repositories/sky020/curriculum/pulls/2
2) Repo owner clicks on "View Diff" button: https://www.dolthub.com/repositories/sky020/curriculum/pulls/2/compare?refName=main
3) See `invalid commit hash provided` error:

<details>
  <summary>Image of error</summary>

![image](https://github.com/dolthub/dolthub-issues/assets/51722130/ca4ba72a-7088-43c0-bd40-45a2b0565dec)

</details>

I can view the diff by clicking on the hash in the PR view, but not the "View Diff" button:

<details>
  <summary>Image of hash</summary>

- https://www.dolthub.com/repositories/sky020/curriculum/pulls/2/compare/us54itp1qbrsk5facdbtj2k7n12lgecj..8uat7njebcee6la9lfa173824ctdjq9n?refName=main

<img width="797" alt="image" src="https://github.com/dolthub/dolthub-issues/assets/51722130/271349cd-7808-4d68-949d-93f74ce25372">

</details>

Note: There are/were some other oddities about this PR (another issue to follow)

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton , thanks for the bug report, I will get a fix out tomorrow.

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton , the error has been resolved now, thanks again for the report :)
