### ISSUE TITLE
unexpected behaviour when dropping tables

### ISSUE THREAD

**Issue by ShaunSHamilton** [dolthub/dolthub-issues#541]
Admittedly, our workflow is _odd_, because we are still in the playing/testing phase of using Dolt. So, some of this could be our fault.

**Workflow**

1) local: drop all tables in database
2) local: run script populating database
    - This script is constantly changed, and one of the frequent changes is table names
3) local: commit changes
4) dolthub: open PR to merge

**Issue**

The dropped tables do not get dropped on the upstream; instead, they are duplicated.

<details>
  <summary>Here is what the Dolthub diff looked like for one such PR</summary>

![image](https://github.com/dolthub/dolthub-issues/assets/51722130/8e6e103a-8116-412d-a235-d07c96a0ae7a)

</details>

The camelCase named tables were dropped. I paired with a colleague on this, and we are both 100% sure, locally, they were dropped. Then, the script created a bunch of tables (this time in snake_case), and this was added, committed, and pushed to be opened in a PR.

We thought the diff was just a bit wonky. So, merged the PR. Then, we noticed the diff was not necessarily _wonky_, but the dropped tables were **not** removed as expected:

<details>
  <summary>Image of `main`</summary>

![image](https://github.com/dolthub/dolthub-issues/assets/51722130/236678bc-c773-482d-81cd-32b1d0216ffb)

</details>

**Expected Behaviour**

The diff, and subsequent merge should have removed the camelCase named tables, and the snake_case named tables should have been added.

_I was not 100% sure where to open this issue. I noticed it in Dolthub, because of the diff view, but please move it._

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton , could you give an example of the workflow or the scripts you ran? It will help us reproduce the bug.

I was able to drop table and merge the changes into main, could you provide me with the script populating database after dropping tables?

Thank you!

**Comment by ShaunSHamilton** [comment]
@liuliu-dev Sorry for the mess: https://github.com/ShaunSHamilton/freeCodeCamp/blob/dolt/dolt/index.js 🙈 

Let me know if anything more could help.

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton thanks for the file.

I could not repro the bug. These are the steps i did:
- check out a branch `drop-table` locally, drop 2 tables `videoLocaleIds` and `usesMultifileEditor`
![Screenshot 2024-04-24 at 10 54 45 AM](https://github.com/dolthub/dolthub-issues/assets/6688812/157c82b3-4115-43b0-bea7-64933c13c7a6)

- modify the constraint of table `assignments`
![Screenshot 2024-04-24 at 10 56 15 AM](https://github.com/dolthub/dolthub-issues/assets/6688812/5b46a263-bdb7-40a9-8442-66e85ed70458)

- commit and push the changes to remote db
- create a pull request from `drop-table` to `main`
- merge the pull request.

this is the diff page of the pull request:

![Screenshot 2024-04-24 at 10 50 29 AM](https://github.com/dolthub/dolthub-issues/assets/6688812/d7a4f9ad-0383-4ab4-89ee-7107008e5781)

the diff looks correct and after merge job finished, the tables are dropped.

Could you give me more details of your workflow to help me identify the issue? Thanks.

**Comment by ShaunSHamilton** [comment]
I am not too sure what more to say.

To clarify, I never adjusted the constraints of any table. The workflow is always:
1) drop ALL tables
2) run script to repopulate database
3) commit + push

My image showing the constraint diff is like that, I assume, because I dropped the table and recreated it.

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton ,

Just a few updates:

I've submitted a pull request to fix the table name list in the diff overview. I expect to merge it either today or tomorrow.

Also, I've successfully replicated the merge issue by cloning your database, but I'm still investigating the cause. I'll keep you posted. Apologies for the inconvenience.

**Comment by liuliu-dev** [comment]
Hi @ShaunSHamilton , do you still have branch `feat/update-tables` locally on database [mot01/curriculum](https://www.dolthub.com/repositories/mot01/curriculum) ? could you check if the camelCase named tables are dropped there? Thank you!

**Comment by ShaunSHamilton** [comment]
@moT01 ☝️

**Comment by moT01** [comment]
I didn't still have the branch locally. I don't quite have my dolt workflow figured out - or I'm not doing it right or something. I have to reclone my fork often. My guess is that it has something to do with git. I have my dolt database folder inside a folder that's a git repo. So when I am switching git branches, and doing other git things, the dolt references get lost or something? There's still a `.dolt` folder there, but `dolt status` gives me "The current directory is not a valid dolt repository." So I try to reclone, and I get this: "data repository already exists: ."  - so I delete the `.dolt` folder and reclone it. 

When I did that, and checkout my `feat/update-tables` branch, the tables do still all exist:

<details>
<summary>images</summary>
<img width="421" alt="Screenshot 2024-04-26 at 8 36 03 AM" src="https://github.com/dolthub/dolthub-issues/assets/20648924/1a23cd71-9842-46c6-8ee1-ef058ab7a75a">
<br>
<img width="231" alt="Screenshot 2024-04-26 at 8 36 11 AM" src="https://github.com/dolthub/dolthub-issues/assets/20648924/f788df7a-6dd8-4e79-a70a-c0f11c9ac9f6">
</details>

**Comment by timsehn** [comment]
You need to add `.dolt` to `.gitignore` or the actual files in the Dolt database will get added to your Git repo. So when you switch branches in Git things will get messed up.

**Comment by liuliu-dev** [comment]
@moT01 Thanks for checking. 

It appears that the camelCase-named tables were not dropped on the `feat/update-tables` branch, which explains why the diff still shows them and why they remain after the merge.

**Comment by ShaunSHamilton** [comment]
Thank you for your time looking into this. I have not experienced this since. So, will close the issue until if comes up again.
