### ISSUE TITLE
dolthub webhook headers

### ISSUE THREAD

**Issue by verdverm** [dolthub/dolthub-issues#543]
I'd like to be able to set headers on webhooks in Dolthub

**Comment by timsehn** [comment]
This is a DoltHub issue. Transferring there.

**Comment by liuliu-dev** [comment]
Hi @verdverm , you can add headers to webhook now, thanks for the feature request :)

![Screenshot 2024-05-23 at 3 22 51 PM](https://github.com/dolthub/dolthub-issues/assets/6688812/b71c6632-4eb3-4b61-9268-942fc0ee9314)
