### ISSUE TITLE
table list doesnt adjust for long table names

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolthub-issues#546]
![Screenshot 2024-09-03 at 11 31 22 AM](https://github.com/user-attachments/assets/3718cdb6-d996-40c2-9e9e-62c7766498e3)

The left side table list doesnt adjust for long table names. This prevents the buttons from being accessible.

**Comment by liuliu-dev** [comment]
Closing the issue since the left-side nav is scrollable.
