### ISSUE TITLE
Show decreasing character limit while typing for pull and issue comments

### ISSUE THREAD

**Issue by katiemcculloch** [dolthub/dolthub-issues#65]
It would be a bummer to write an enormous comment and then realize you can't post it. This adds transparency for what length is accepted. We can also discuss raising character limit if needed.

This could also be useful for database/issue/pull request descriptions

Can see the max length allowed in these [wire validation files](https://github.com/dolthub/ld/blob/main/go/services/dolthubapi/pkg/service/internal/wire/issue_validate.go#L156) in dolthubapi

**Comment by tbantle22** [comment]
Related to https://github.com/dolthub/dolthub-issues/issues/30. We probably should increase the limit in addition to this

**Comment by cheshirekate8** [comment]
Finished for comment, will create a new issue for adding char count to database/issue/pull request descriptions as needed!
