### ISSUE TITLE
Add featured image to blog post

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#71]
In a blog post, you should be able to add a field to the frontmatter designating a featured image to use, and then the blog should use whatever meta tags or other techniques it needs to get as many sites/apps as possible to respect it.

https://www.gatsbyjs.com/docs/working-with-images-in-markdown/

**Comment by ElTragon** [comment]
Done. All link now have a default image, you can set your own image by following the readme
https://github.com/dolthub/ld/tree/main/web/packages/blog#featured-image
