### ISSUE TITLE
Stable URLs for DoltHub named queries

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolthub-issues#75]
I think it would make sense to change the URL for named queries to contain the query name rather than the query itself. The latter is very useful to be able to share ad-hoc queries, but I think that for named queries it would be good if the URL didn't change (see https://www.w3.org/Provider/Style/URI), as that would let me as a repository maintainer update the query when the schema changes and the URL remains correct.

**Comment by tbantle22** [comment]
Fix for this was released

**Comment by knutwannheden** [comment]
Not sure if it is intentional but I suspect it might be small glitch: When I navigate to a named query and then click on the dropdown to select another branch, then the URL switches back to contain the encoded query again.

Because that was going to be my next question: How would I share a link to the query on a specific branch or possibly even specific commit so that I can reference a query at a point in time (kind of like I can refer to a file in a GitHub repo for a given branch or commit) and know that the query will operate on a given set of data.

**Comment by tbantle22** [comment]
I'll fix that branch selector behavior today. The path https://www.dolthub.com/repositories/[owner]/[repository]/query/[ref name]?name=[query name] works

**Comment by tbantle22** [comment]
> Not sure if it is intentional but I suspect it might be small glitch: When I navigate to a named query and then click on the dropdown to select another branch, then the URL switches back to contain the encoded query again.

This has been fixed now
