### ISSUE TITLE
Improve language on Edit table screen

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#82]
**Describe the solution you'd like**
I'm not entirely sure whether it is trying to "Write a SQL query" or "Run a SQL query" 

**Describe alternatives you've considered**
While the combination of "Write" and "Run" in a sentence is certainly _unique_, it doesn't make much sense.

**Additional context**
![image](https://user-images.githubusercontent.com/40151222/136446966-b81cbea0-7bfb-405c-a764-a4d25d37dc17.png)

**Comment by tbantle22** [comment]
We simplified the language a bit. Hope that's clearer
<img width="954" alt="Screen Shot 2021-10-08 at 3 27 44 PM" src="https://user-images.githubusercontent.com/29443194/136631105-d18a5682-f976-4323-ba7e-7079ed5811a9.png">
