### ISSUE TITLE
Spreadsheet Editor Enhancement

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolthub-issues#98]
### **Is your feature request related to a problem? Please describe.**
Clicking on `Add Row` adds a row *somewhere*, pretty sure it's the at the bottom. If the table is of any decent size, it's difficult to find the added rows to edit them. 

### **Describe the solution you'd like**
Perhaps add them to the top, or limit the number (and have a textbox notifying the user that the full table isn't being displayed), and just add the rows onto the bottom of that.

### **Describe alternatives you've considered**
Limit number of rows displayed **or** add rows on top (and then under the new row)

### **Additional context**
![image](https://user-images.githubusercontent.com/40151222/138460197-1824dd1d-c21a-49b5-913a-9f8e0d4f5d53.png)
#### Added rows are the 250th row
![image](https://user-images.githubusercontent.com/40151222/138460294-767e7ca6-0389-4ca3-a78e-7d16e91a5923.png)

#### Once it finishes loading more rows, the new rows are sandwiched between old rows, making them potentially harder to spot
![Uploading image.png…]()

**Comment by tbantle22** [comment]
Added an insert dropdown with more options
<img width="442" alt="139509330-e11e8929-4fd7-42c5-8786-4b591ddb5aa4" src="https://user-images.githubusercontent.com/29443194/139715943-b087e7d0-719b-474e-abce-02cf2002d4eb.png">
