### ISSUE TITLE
Add hyperlink to allow navigating referenced rows

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolthub-issues#99]
**Is your feature request related to a problem? Please describe.**
When browsing the data of a repo I see foreign keys for other tables but can't easily navigate to the referenced row.

**Describe the solution you'd like**
When clicking on a data cell for which it is known to be a foreign key for a certain other table (this is for instance the case when browsing the data of a given table but will not always be possible when viewing the result from some arbitrary query with projected values), it would be nice if the icon with the context actions would allow navigating to the referenced row.

**Describe alternatives you've considered**

**Additional context**

**Comment by liuliu-dev** [comment]
Hey @knutwannheden , we now have links to reference rows, thanks for the feature request!

if you go to cell dropdown, then follow the reference, you will see the referenced tables, click a table and it will get you to the referenced rows:

<img width="548" alt="Screen Shot 2022-04-13 at 11 29 10 AM" src="https://user-images.githubusercontent.com/6688812/163246643-3ad56295-aba7-4b72-b645-b5ed09c21242.png">
